## ASHRAE 140-2023

Section 7: CASE 600 - South windows base case

_OpenSimula: v 0.2_

In [2]:
import OpenSimula as osm
import pandas as pd
import numpy as np

case600_dict = {
    "name": "Case 600",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "components": [
        {
            "type": "File_met",
            "name": "Denver",
            "file_type": "TMY3",
            "file_name": "../../mets/725650TY.tmy3"
        },
        {
            "type": "Material",
            "name": "Plasterboard",
            "conductivity": 0.16,
            "density": 950,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Fiberglass_quilt",
            "conductivity": 0.04,
            "density": 12,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Wood_siding",
            "conductivity": 0.14,
            "density": 530,
            "specific_heat": 900
        },
        {
            "type": "Material",
            "name": "Insulation",
            "conductivity": 0.04,
            "density": 0.1,
            "specific_heat": 0.1
        },
        {
            "type": "Material",
            "name": "Timber_flooring",
            "conductivity": 0.14,
            "density": 650,
            "specific_heat": 1200
        },
        {
            "type": "Material",
            "name": "Roofdeck",
            "conductivity": 0.14,
            "density": 530,
            "specific_heat": 900
        },
        {
            "type": "Construction",
            "name": "Wall",
            "solar_alpha": [
                0.6,
                0.6
            ],
            "materials": [
                "Wood_siding",
                "Fiberglass_quilt",
                "Plasterboard"
            ],
            "thicknesses": [
                0.009,
                0.066,
                0.012
            ]
        },
        {
            "type": "Construction",
            "name": "Floor",
            "solar_alpha": [
                0,
                0.6
            ],
            "materials": [
                "Insulation",
                "Timber_flooring"
            ],
            "thicknesses": [
                1.003,
                0.025
            ]
        },
        {
            "type": "Construction",
            "name": "Roof",
            "solar_alpha": [
                0.6,
                0.6
            ],
            "materials": [
                "Roofdeck",
                "Fiberglass_quilt",
                "Plasterboard"
            ],
            "thicknesses": [
                0.019,
                0.1118,
                0.010
            ]
        },
        {
            "type": "Glazing",
            "name": "double_glazing",
            "solar_tau": 0.703,
            "solar_rho": [
                0.128,
                0.128
            ],
            "g": [
                0.769,
                0.769
            ],
            "lw_epsilon": [
                0.84,
                0.84
            ],
            "U": 2.722,
            "f_tau_nor": "-0.1175 * cos_theta^3 - 1.0295 * cos_theta^2 + 2.1354 * cos_theta",
            "f_1_minus_rho_nor": [
                "1.114 * cos_theta^3 - 3.209 * cos_theta^2 + 3.095 * cos_theta",
                "1.114 * cos_theta^3 - 3.209 * cos_theta^2 + 3.095 * cos_theta"
            ]
        },
        {
            "type": "Opening_type",
            "name": "Window",
            "glazing": "double_glazing",
            "frame_fraction": 0,
            "glazing_fraction": 1
        },
        {
            "type": "Space_type",
            "name": "constant_gain_space",
            "people_density": "0",
            "light_density": "0",
            "other_gains_density": "4.1667",
            "other_gains_radiant_fraction": 0.6,
            "infiltration": "0.5"
        },
        {
            "type": "Building",
            "name": "Building",
            "file_met": "Denver",
            "albedo": 0.2,
            "azimuth": 0,
            "shadow_calculation": "INSTANT"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Building",
            "space_type": "constant_gain_space",
            "floor_area": 48,
            "volume": 129.6,
            "furniture_weight": 0
        },
        {
            "type": "Exterior_surface",
            "name": "north_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                8,
                6,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 180,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "east_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                8,
                0,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": 90,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "south_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 0,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Opening",
            "name": "south_window_1",
            "surface": "south_wall",
            "opening_type": "Window",
            "ref_point": [
                0.5,
                0.2
            ],
            "width": 3,
            "height": 2,
            "h_cv": [
                8.0,
                2.4
            ]
        },
        {
            "type": "Opening",
            "name": "south_window_2",
            "surface": "south_wall",
            "opening_type": "Window",
            "ref_point": [
                4.5,
                0.2
            ],
            "width": 3,
            "height": 2,
            "h_cv": [
                8.0,
                2.4
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "west_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": -90,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "roof_wall",
            "construction": "Roof",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                2.7
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": 90,
            "h_cv": [
                14.4,
                1.8
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "floor_wall",
            "construction": "Floor",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": -90,
            "h_cv": [
                0.8,
                2.2
            ]
        },
        {
            "type": "HVAC_perfect_system",
            "name": "system",
            "space": "space_1",
            "file_met": "Denver",
            "outdoor_air_flow": "0",
            "heating_setpoint": "20",
            "cooling_setpoint": "27",
            "system_on_off": "1"
        }
    ]
}


sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_dict(case600_dict)

Reading project data from dictonary
Reading completed.
Checking project: Case 600
ok

In [3]:
pro.component("Building").show3D()

Widget(value='<iframe src="http://localhost:54456/index.html?ui=P_0x1076c9a90_0&reconnect=auto" class="pyvista…

In [4]:
pro.simulate()

Calculating solar direct shadows ...
Calculating solar diffuse shadows ...
Simulating Case 600: ...
10%: N_iter: 2.87
20%: N_iter: 2.85
30%: N_iter: 2.83
40%: N_iter: 2.70
50%: N_iter: 2.58
60%: N_iter: 2.54
70%: N_iter: 2.54
80%: N_iter: 2.76
90%: N_iter: 2.84
100%: N_iter: 2.88
Simulation completed.

In [5]:
# Heating and Cooling Loads
load = pro.component("space_1").variable("system_sensible_heat").values
annual_heating = np.where(load>0,load,0).sum()/1e6
annual_cooling = np.where(load<0,-load,0).sum()/1e6
peak_heating = load.max()/1000
i_peak_heating = np.argmax(load)
peak_cooling = -load.min()/1000
i_peak_cooling = np.argmin(load)

print("Anual Heating (MWh): ", annual_heating)
print("Anual Coolling (MWh): ",annual_cooling)
print("Peak Heating (kW): ", peak_heating)
print("Peak Cooling (kW): ", peak_cooling)
print("Peak Heating Date: ",pro.dates()[i_peak_heating])
print("Peak Cooling Date: ",pro.dates()[i_peak_cooling])

Anual Heating (MWh):  4.495504964436392
Anual Coolling (MWh):  5.970638233263562
Peak Heating (kW):  3.256134521943883
Peak Cooling (kW):  5.782115714532082
Peak Heating Date:  2001-12-31 23:30:00
Peak Cooling Date:  2001-01-22 13:30:00

In [6]:
# Solar Radiation
hor_sol_rad = pro.component("roof_wall").variable("E_dir").values.sum()/1000 + pro.component("roof_wall").variable("E_dif").values.sum()/1000
north_sol_rad = pro.component("north_wall").variable("E_dir").values.sum()/1000 + pro.component("north_wall").variable("E_dif").values.sum()/1000
east_sol_rad = pro.component("east_wall").variable("E_dir").values.sum()/1000 + pro.component("east_wall").variable("E_dif").values.sum()/1000
south_sol_rad = pro.component("south_wall").variable("E_dir").values.sum()/1000 + pro.component("south_wall").variable("E_dif").values.sum()/1000
west_sol_rad = pro.component("west_wall").variable("E_dir").values.sum()/1000 + pro.component("west_wall").variable("E_dif").values.sum()/1000
window_trans =  pro.component("south_window_1").variable("E_dir_tra").values.sum()/1000 + pro.component("south_window_1").variable("E_dif_tra").values.sum()/1000

print("Horizontal solar rad. (kWh/m²): ",hor_sol_rad)
print("North solar rad. (kWh/m²): ", north_sol_rad)
print("East solar rad. (kWh/m²): ",east_sol_rad)
print("South solar rad. (kWh/m²): ",south_sol_rad)
print("West solar rad. (kWh/m²): ", west_sol_rad)
print ("Window transmitted solar rad. (kWh/m²): ",window_trans)
print (pro.component("double_glazing").tau_solar_diffuse)

Horizontal solar rad. (kWh/m²):  1670.1705570453885
North solar rad. (kWh/m²):  483.03435800721417
East solar rad. (kWh/m²):  1077.0226681280733
South solar rad. (kWh/m²):  1363.5595379116871
West solar rad. (kWh/m²):  981.7733555338101
Window transmitted solar rad. (kWh/m²):  810.6511458784576
0.60588055

In [7]:
# Sky temperature
t_sky_average = pro.component("Denver").variable("sky_temperature").values.mean()
t_sky_min = pro.component("Denver").variable("sky_temperature").values.min()
i_t_sky_min = np.argmin(pro.component("Denver").variable("sky_temperature").values)
t_sky_max = pro.component("Denver").variable("sky_temperature").values.max()
i_t_sky_max= np.argmax(pro.component("Denver").variable("sky_temperature").values)

print("Average sky temp (ºC): ",t_sky_average)
print("Min. sky temp (ºC): ",t_sky_min)
print("Max. sky temp (ºC): ",t_sky_max)
print("Min. sky temp date: ",pro.dates()[i_t_sky_min])
print("Max. sky temp date: ",pro.dates()[i_t_sky_max])

Average sky temp (ºC):  -1.985010322048502
Min. sky temp (ºC):  -37.95756585462965
Max. sky temp (ºC):  26.05027737992407
Min. sky temp date:  2001-12-31 23:30:00
Max. sky temp date:  2001-08-04 14:30:00

In [8]:
aux = pro.component("system").variable_dataframe(frequency="M",value="sum", pos_neg_columns=["Q_sensible"])
df_month_loads = pd.DataFrame() 
df_month_loads["Heating (kWh)"] = aux["Q_sensible_pos"]/1000
df_month_loads["Cooling (kWh)"] = -aux["Q_sensible_neg"]/1000
df_month_loads.to_clipboard()
df_month_loads

            Heating (kWh)  Cooling (kWh)
date
2001-01-31     730.835702     487.163638
2001-02-28     695.661097     368.173951
2001-03-31     495.376657     468.283579
2001-04-30     521.986703     249.797907
2001-05-31     149.710124     355.183967
2001-06-30      14.445045     554.303961
2001-07-31      14.584151     549.475577
2001-08-31      10.733450     663.340658
2001-09-30      87.409405     732.983086
2001-10-31     367.655624     661.440085
2001-11-30     645.641329     427.501032
2001-12-31     761.465676     452.990792

In [9]:
def dates_month_max_min(df,variable):
    dates_max = []
    dates_min = []
    for mes in range(1,13):
        df_mes = df[df["date"].dt.month == mes]
        dates_max.append(df_mes["date"][df_mes[variable].idxmax()])
        dates_min.append(df_mes["date"][df_mes[variable].idxmin()])
    return (dates_max,dates_min)


df_month_peak_loads = pd.DataFrame()
dates_heating, dates_cooling = dates_month_max_min(pro.component("system").variable_dataframe(),"Q_sensible")
df_month_peak_loads["Heating (kW)"] = pro.component("system").variable_dataframe(frequency="M",value="max")["Q_sensible"]
df_month_peak_loads["Heating (kW)"] = df_month_peak_loads["Heating (kW)"]/1000
df_month_peak_loads["Cooling (kW)"] = pro.component("system").variable_dataframe(frequency="M",value="min")["Q_sensible"]
df_month_peak_loads["Cooling (kW)"] = -df_month_peak_loads["Cooling (kW)"]/1000
df_month_peak_loads["Heating dates"] = dates_heating
df_month_peak_loads["Cooling dates"] = dates_cooling
df_month_peak_loads.to_clipboard()
df_month_peak_loads

            Heating (kW)  Cooling (kW)       Heating dates       Cooling dates
date
2001-01-31      2.965311      5.782116 2001-01-04 03:30:00 2001-01-22 13:30:00
2001-02-28      3.107934      4.844697 2001-02-09 05:30:00 2001-02-15 13:30:00
2001-03-31      2.209755      4.629485 2001-03-17 05:30:00 2001-03-09 13:30:00
2001-04-30      2.388594      3.897257 2001-04-11 04:30:00 2001-04-07 13:30:00
2001-05-31      1.674815      3.156698 2001-05-01 03:30:00 2001-05-10 13:30:00
2001-06-30      0.881179      3.288276 2001-06-09 04:30:00 2001-06-26 13:30:00
2001-07-31      0.602637      3.449832 2001-07-26 04:30:00 2001-07-29 13:30:00
2001-08-31      0.581020      4.477265 2001-08-17 05:30:00 2001-08-27 12:30:00
2001-09-30      1.228912      5.293188 2001-09-28 23:30:00 2001-09-30 13:30:00
2001-10-31      1.720522      5.643380 2001-10-06 06:30:00 2001-10-18 13:30:00
2001-11-30      3.116165      5.481923 2001-11-26 06:30:00 2001-11-28 13:30:00
2001-12-31      3.256135      5.681528 2001-12-31 23:30:00 2001-12-01 13:30:00

In [10]:
# 4-MAY
day_df= pd.DataFrame()
intervalo = ["2001-05-04","2001-05-05"]
aux = pro.component("roof_wall").variable_dataframe(interval=intervalo)
day_df["Hor. rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("south_wall").variable_dataframe(interval=intervalo)
day_df["South rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("west_wall").variable_dataframe(interval=intervalo)
day_df["West rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux =  pro.component("south_window_1").variable_dataframe(interval=intervalo)
day_df["Window trans. rad. (W/m²)"] = aux["E_dir_tra"] +  aux["E_dif_tra"]
aux =  pro.component("Denver").variable_dataframe(interval=intervalo)
day_df["Sky temp. (ºC)"] = aux["sky_temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

,Hor. rad. (W/m²),South rad. (W/m²),West rad. (W/m²),Window trans. rad. (W/m²),Sky temp. (ºC),Load (kWh)
2952,0.0,0.0,0.0,0.000000,-1.509956,1.056580
2953,0.0,0.0,0.0,0.000000,-0.897172,1.102513
2954,0.0,0.0,0.0,0.000000,-1.509956,1.165271
2955,0.0,0.0,0.0,0.000000,-1.509956,1.195069
2956,0.0,0.0,0.0,0.000000,-1.509956,1.212413
2957,15.0,9.0,9.0,5.452925,-1.509956,1.189198
2958,60.0,36.0,36.0,21.811700,-0.897172,1.048228
2959,111.0,66.6,66.6,40.351645,-0.782669,0.864123
2960,158.0,94.8,94.8,57.437476,-0.329572,0.631000
2961,195.0,117.0,117.0,70.888024,1.351987,0.348916
2962,263.0,157.8,157.8,95.607951,2.306782,0.005843
2963,278.0,166.8,166.8,101.060876,1.941959,0.000000
2964,277.0,166.2,166.2,100.697347,0.150952,0.000000
2965,259.0,155.4,155.4,94.153837,-0.897172,0.000000
2966,227.0,136.2,136.2,82.520931,-2.733323,0.000000
2967,181.0,108.6,108.6,65.798628,-1.509956,0.034013
2968,104.0,62.4,62.4,37.806946,-1.969887,0.366067
2969,53.0,31.8,31.8,19.267001,-2.115965,0.648013
2970,11.0,6.6,6.6,3.998812,-2.557878,0.925712
2971,0.0,0.0,0.0,0.000000,-3.198825,1.123449
2972,0.0,0.0,0.0,0.000000,-3.198825,1.229690
2973,0.0,0.0,0.0,0.000000,-4.066853,1.320955
2974,0.0,0.0,0.0,0.000000,-5.260735,1.420412
2975,0.0,0.0,0.0,0.000000,-5.260735,1.465200

In [11]:
# 1-FEB
day_df= pd.DataFrame()
intervalo = ["2001-02-01","2001-02-02"]
aux = pro.component("roof_wall").variable_dataframe(interval=intervalo)
day_df["Hor. rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("south_wall").variable_dataframe(interval=intervalo)
day_df["South rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("west_wall").variable_dataframe(interval=intervalo)
day_df["West rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux =  pro.component("south_window_1").variable_dataframe(interval=intervalo)
day_df["Window trans. rad. (W/m²)"] = aux["E_dir_tra"] +  aux["E_dif_tra"]
aux =  pro.component("Denver").variable_dataframe(interval=intervalo)
day_df["Sky temp. (ºC)"] = aux["sky_temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

,Hor. rad. (W/m²),South rad. (W/m²),West rad. (W/m²),Window trans. rad. (W/m²),Sky temp. (ºC),Load (kWh)
744,0.000000,0.000000,0.000000,0.000000,-23.447622,2.191421
745,0.000000,0.000000,0.000000,0.000000,-23.872637,2.260840
746,0.000000,0.000000,0.000000,0.000000,-26.084956,2.325685
747,0.000000,0.000000,0.000000,0.000000,-27.912259,2.389584
748,0.000000,0.000000,0.000000,0.000000,-26.214853,2.385226
749,0.000000,0.000000,0.000000,0.000000,-26.910724,2.419006
750,0.000000,0.000000,0.000000,0.000000,-27.561544,2.409687
751,37.101279,208.702140,9.800000,107.844221,-25.722382,1.743291
752,209.000000,511.760800,34.900000,309.855358,-25.023357,0.254042
753,383.000000,727.136727,57.800000,477.433252,-24.047287,0.000000
754,516.000000,874.542168,75.100000,594.536163,-22.303806,-1.512283
755,592.000000,954.997342,84.700000,656.682390,-21.242496,-3.122633
756,606.000000,969.673325,169.890343,667.652213,-19.318116,-4.113384
757,554.000000,913.820158,414.861100,625.241890,-21.700079,-4.282911
758,443.000000,793.012191,607.401901,530.225512,-21.815336,-4.006735
759,284.000000,607.800366,702.283681,383.029266,-22.396291,-3.134916
760,103.000000,348.356547,598.045623,194.131265,-23.091088,-1.672324
761,3.000000,1.800000,1.800000,1.090585,-25.644371,0.000000
762,0.000000,0.000000,0.000000,0.000000,-26.115605,0.000000
763,0.000000,0.000000,0.000000,0.000000,-26.811674,0.800227
764,0.000000,0.000000,0.000000,0.000000,-28.140965,1.569041
765,0.000000,0.000000,0.000000,0.000000,-29.260291,2.027309
766,0.000000,0.000000,0.000000,0.000000,-29.416416,2.282232
767,0.000000,0.000000,0.000000,0.000000,-29.004085,2.402924

In [12]:
# 14-JUL
day_df= pd.DataFrame()
intervalo = ["2001-07-14","2001-07-15"]
aux = pro.component("roof_wall").variable_dataframe(interval=intervalo)
day_df["Hor. rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("south_wall").variable_dataframe(interval=intervalo)
day_df["South rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("west_wall").variable_dataframe(interval=intervalo)
day_df["West rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux =  pro.component("south_window_1").variable_dataframe(interval=intervalo)
day_df["Window trans. rad. (W/m²)"] = aux["E_dir_tra"] +  aux["E_dif_tra"]
aux =  pro.component("Denver").variable_dataframe(interval=intervalo)
day_df["Sky temp. (ºC)"] = aux["sky_temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

,Hor. rad. (W/m²),South rad. (W/m²),West rad. (W/m²),Window trans. rad. (W/m²),Sky temp. (ºC),Load (kWh)
4656,0.0,0.000000,0.000000,0.000000,4.128365,0.000000
4657,0.0,0.000000,0.000000,0.000000,3.648777,0.000000
4658,0.0,0.000000,0.000000,0.000000,2.514234,0.000000
4659,0.0,0.000000,0.000000,0.000000,1.463941,0.000000
4660,2.0,1.200000,1.200000,0.727057,0.321597,0.027425
4661,90.0,20.500000,20.500000,12.420551,2.948471,0.000000
4662,275.0,46.000000,46.000000,27.870505,5.535130,0.000000
4663,479.0,73.400000,73.400000,44.471632,7.321400,0.000000
4664,668.0,169.603829,98.800000,70.231291,9.174255,0.000000
4665,827.0,299.552804,119.200000,119.665913,12.000253,-0.607056
4666,941.0,394.315790,133.600000,172.009090,13.092097,-1.600410
4667,1003.0,445.367964,141.300000,205.034298,13.373687,-2.287685
4668,1008.0,449.285733,236.945012,207.623861,14.259543,-2.731767
4669,955.0,405.619764,473.472680,178.894981,14.504961,-2.883736
4670,848.0,317.091962,671.254933,128.337804,15.304747,-2.722725
4671,696.0,191.665710,808.452844,76.483743,14.504961,-2.309619
4672,509.0,77.400000,861.826785,46.895155,14.652104,-1.882431
4673,306.0,50.100000,808.257445,30.354616,13.053418,-1.465016
4674,114.0,23.900000,592.811027,14.480545,11.825351,-1.042227
4675,5.0,3.000000,3.000000,1.817642,11.273864,-0.547720
4676,0.0,0.000000,0.000000,0.000000,8.187216,-0.169090
4677,0.0,0.000000,0.000000,0.000000,7.703522,0.000000
4678,0.0,0.000000,0.000000,0.000000,6.814796,0.000000
4679,0.0,0.000000,0.000000,0.000000,5.464789,0.000000