## ASHRAE 140-2023

Section 7: CASE 900 - High-Mass Base Building

_OpenSimula: v0.2_

In [1]:
import OpenSimula as osm
import pandas as pd
import numpy as np

case900_dict = {
    "name": "Case 900",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "components": [
        {
            "type": "File_met",
            "name": "Denver",
            "file_type": "TMY3",
            "file_name": "725650TY.tmy3"
        },
        {
            "type": "Material",
            "name": "Concrete_block",
            "conductivity": 0.51,
            "density": 1400,
            "specific_heat": 1000
        },
        {
            "type": "Material",
            "name": "Concrete_slab",
            "conductivity": 1.13,
            "density": 1400,
            "specific_heat": 1000
        },
        {
            "type": "Material",
            "name": "Plasterboard",
            "conductivity": 0.16,
            "density": 950,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Fiberglass_quilt",
            "conductivity": 0.04,
            "density": 12,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Wood_siding",
            "conductivity": 0.14,
            "density": 530,
            "specific_heat": 900
        },
        {
            "type": "Material",
            "name": "Foam_insulation",
            "conductivity": 0.04,
            "density": 10,
            "specific_heat": 1400
        },
        {
            "type": "Material",
            "name": "Insulation",
            "conductivity": 0.04,
            "density": 0.1,
            "specific_heat": 0.1
        },
        {
            "type": "Material",
            "name": "Timber_flooring",
            "conductivity": 0.14,
            "density": 650,
            "specific_heat": 1200
        },
        {
            "type": "Material",
            "name": "Roofdeck",
            "conductivity": 0.14,
            "density": 530,
            "specific_heat": 900
        },
        {
            "type": "Construction",
            "name": "Wall",
            "solar_alpha": [
                0.6,
                0.6
            ],
            "materials": [
                "Wood_siding",
                "Foam_insulation",
                "Concrete_block"
            ],
            "thicknesses": [
                0.009,
                0.0615,
                0.100
            ]
        },
        {
            "type": "Construction",
            "name": "Floor",
            "solar_alpha": [
                0,
                0.6
            ],
            "materials": [
                "Insulation",
                "Concrete_slab"
            ],
            "thicknesses": [
                1.007,
                0.080
            ]
        },
        {
            "type": "Construction",
            "name": "Roof",
            "solar_alpha": [
                0.6,
                0.6
            ],
            "materials": [
                "Roofdeck",
                "Fiberglass_quilt",
                "Plasterboard"
            ],
            "thicknesses": [
                0.019,
                0.1118,
                0.010
            ]
        },
        {
            "type": "Glazing",
            "name": "double_glazing",
            "solar_tau": 0.703,
            "solar_rho": [
                0.128,
                0.128
            ],
            "g": [
                0.769,
                0.769
            ],
            "lw_epsilon": [
                0.84,
                0.84
            ],
            "U": 2.722,
            "f_tau_nor": "-0.1175 * cos_theta^3 - 1.0295 * cos_theta^2 + 2.1354 * cos_theta",
            "f_1_minus_rho_nor": [
                "1.114 * cos_theta^3 - 3.209 * cos_theta^2 + 3.095 * cos_theta",
                "1.114 * cos_theta^3 - 3.209 * cos_theta^2 + 3.095 * cos_theta"
            ]
        },
        {
            "type": "Opening_type",
            "name": "Window",
            "glazing": "double_glazing",
            "frame_fraction": 0,
            "glazing_fraction": 1
        },
        {
            "type": "Space_type",
            "name": "constant_gain_space",
            "people_density": "0",
            "light_density": "0",
            "other_gains_density": "4.1667",
            "other_gains_radiant_fraction": 0.6,
            "infiltration": "0.5"
        },
        {
            "type": "Building",
            "name": "Building",
            "file_met": "Denver",
            "albedo": 0.2,
            "azimuth": 0,
            "shadow_calculation": "INSTANT"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Building",
            "space_type": "constant_gain_space",
            "floor_area": 48,
            "volume": 129.6,
            "furniture_weight": 0
        },
        {
            "type": "Exterior_surface",
            "name": "north_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                8,
                6,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 180,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "east_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                8,
                0,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": 90,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "south_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 0,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Opening",
            "name": "south_window_1",
            "surface": "south_wall",
            "opening_type": "Window",
            "ref_point": [
                0.5,
                0.2
            ],
            "width": 3,
            "height": 2,
            "h_cv": [
                8.0,
                2.4
            ]
        },
        {
            "type": "Opening",
            "name": "south_window_2",
            "surface": "south_wall",
            "opening_type": "Window",
            "ref_point": [
                4.5,
                0.2
            ],
            "width": 3,
            "height": 2,
            "h_cv": [
                8.0,
                2.4
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "west_wall",
            "construction": "Wall",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": -90,
            "altitude": 0,
            "h_cv": [
                11.9,
                2.2
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "roof_wall",
            "construction": "Roof",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                2.7
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": 90,
            "h_cv": [
                14.4,
                1.8
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "floor_wall",
            "construction": "Floor",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": -90,
            "h_cv": [
                0.8,
                2.2
            ]
        },
        {
            "type": "HVAC_perfect_system",
            "name": "system",
            "space": "space_1",
            "file_met": "Denver",
            "outdoor_air_flow": "0",
            "heating_setpoint": "20",
            "cooling_setpoint": "27",
            "system_on_off": "1"
        }
    ]
}


sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_dict(case900_dict)

Reading project data from dictonary
Reading completed.
Checking project: Case 900
ok

In [2]:
pro.simulate()

Calculating solar direct shadows ...
Calculating solar diffuse shadows ...
Simulating Case 900: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End

In [3]:
# Heating and Cooling Loads
load = pro.component("space_1").variable("system_sensible_heat").values
annual_heating = np.where(load>0,load,0).sum()/1e6
annual_cooling = np.where(load<0,-load,0).sum()/1e6
peak_heating = load.max()/1000
i_peak_heating = np.argmax(load)
peak_cooling = -load.min()/1000
i_peak_cooling = np.argmin(load)

print("Anual Heating (MWh): ", annual_heating)
print("Anual Coolling (MWh): ",annual_cooling)
print("Peak Heating (kW): ", peak_heating)
print("Peak Cooling (kW): ", peak_cooling)
print("Peak Heating Date: ",pro.dates()[i_peak_heating])
print("Peak Cooling Date: ",pro.dates()[i_peak_cooling])

Anual Heating (MWh):  1.7837020005253246
Anual Coolling (MWh):  2.5991847736392453
Peak Heating (kW):  2.690848039682748
Peak Cooling (kW):  2.8458043687977734
Peak Heating Date:  2001-02-09 05:30:00
Peak Cooling Date:  2001-10-01 13:30:00

In [4]:
aux = pro.component("system").variable_dataframe(frequency="M",value="sum", pos_neg_columns=["Q_sensible"])
df_month_loads = pd.DataFrame() 
df_month_loads["Heating (kWh)"] = aux["Q_sensible_pos"]/1000
df_month_loads["Cooling (kWh)"] = -aux["Q_sensible_neg"]/1000
df_month_loads.to_clipboard()
df_month_loads

            Heating (kWh)  Cooling (kWh)
date
2001-01-31     281.003293      49.672094
2001-02-28     316.077830      12.827583
2001-03-31     140.193225      66.468344
2001-04-30     273.526705      25.416329
2001-05-31      34.527403     130.674962
2001-06-30       0.000000     422.561007
2001-07-31       0.000000     419.780665
2001-08-31       0.000000     537.647082
2001-09-30       0.141134     506.891365
2001-10-31      86.356276     297.668221
2001-11-30     313.701318      72.036827
2001-12-31     338.174818      57.540294

In [5]:
def dates_month_max_min(df,variable):
    dates_max = []
    dates_min = []
    for mes in range(1,13):
        df_mes = df[df["date"].dt.month == mes]
        dates_max.append(df_mes["date"][df_mes[variable].idxmax()])
        dates_min.append(df_mes["date"][df_mes[variable].idxmin()])
    return (dates_max,dates_min)


df_month_peak_loads = pd.DataFrame()
dates_heating, dates_cooling = dates_month_max_min(pro.component("system").variable_dataframe(),"Q_sensible")
df_month_peak_loads["Heating (kW)"] = pro.component("system").variable_dataframe(frequency="M",value="max")["Q_sensible"]
df_month_peak_loads["Heating (kW)"] = df_month_peak_loads["Heating (kW)"]/1000
df_month_peak_loads["Cooling (kW)"] = pro.component("system").variable_dataframe(frequency="M",value="min")["Q_sensible"]
df_month_peak_loads["Cooling (kW)"] = -df_month_peak_loads["Cooling (kW)"]/1000
df_month_peak_loads["Heating dates"] = dates_heating
df_month_peak_loads["Cooling dates"] = dates_cooling
df_month_peak_loads.to_clipboard()
df_month_peak_loads

            Heating (kW)  Cooling (kW)       Heating dates       Cooling dates
date
2001-01-31      2.047974      1.898919 2001-01-29 06:30:00 2001-01-22 14:30:00
2001-02-28      2.690848      0.959157 2001-02-09 05:30:00 2001-02-15 14:30:00
2001-03-31      1.826365      1.566075 2001-03-17 05:30:00 2001-03-11 13:30:00
2001-04-30      2.019377      1.180197 2001-04-03 02:30:00 2001-04-07 14:30:00
2001-05-31      1.267105      1.649597 2001-05-01 05:30:00 2001-05-11 13:30:00
2001-06-30      0.000000      1.996276 2001-06-01 00:30:00 2001-06-14 13:30:00
2001-07-31      0.000000      2.023895 2001-07-01 04:30:00 2001-07-17 13:30:00
2001-08-31      0.000000      2.501316 2001-08-01 05:30:00 2001-08-29 13:30:00
2001-09-30      0.093038      2.794700 2001-09-29 06:30:00 2001-09-11 14:30:00
2001-10-31      1.386507      2.845804 2001-10-07 06:30:00 2001-10-01 13:30:00
2001-11-30      2.403645      2.064302 2001-11-26 07:30:00 2001-11-22 13:30:00
2001-12-31      2.218177      1.884167 2001-12-31 07:30:00 2001-12-02 14:30:00

In [6]:
# 1-FEB
day_df= pd.DataFrame()
intervalo = ["2001-02-01","2001-02-02"]
aux = pro.component("roof_wall").variable_dataframe(interval=intervalo)
day_df["Hor. rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("south_wall").variable_dataframe(interval=intervalo)
day_df["South rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("west_wall").variable_dataframe(interval=intervalo)
day_df["West rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux =  pro.component("south_window_1").variable_dataframe(interval=intervalo)
day_df["Window trans. rad. (W/m²)"] = aux["E_dir_tra"] +  aux["E_dif_tra"]
aux =  pro.component("Denver").variable_dataframe(interval=intervalo)
day_df["Sky temp. (ºC)"] = aux["sky_temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

,Hor. rad. (W/m²),South rad. (W/m²),West rad. (W/m²),Window trans. rad. (W/m²),Sky temp. (ºC),Load (kWh)
744,0.000000,0.000000,0.000000,0.000000,-23.447622,1.111616
745,0.000000,0.000000,0.000000,0.000000,-23.872637,1.226809
746,0.000000,0.000000,0.000000,0.000000,-26.084956,1.339538
747,0.000000,0.000000,0.000000,0.000000,-27.912259,1.449363
748,0.000000,0.000000,0.000000,0.000000,-26.214853,1.511096
749,0.000000,0.000000,0.000000,0.000000,-26.910724,1.603475
750,0.000000,0.000000,0.000000,0.000000,-27.561544,1.657196
751,37.101279,208.702140,9.800000,107.844221,-25.722382,1.414990
752,209.000000,511.760800,34.900000,309.855358,-25.023357,0.815669
753,383.000000,727.136727,57.800000,477.433252,-24.047287,0.148265
754,516.000000,874.542168,75.100000,594.536163,-22.303806,0.000000
755,592.000000,954.997342,84.700000,656.682390,-21.242496,0.000000
756,606.000000,969.673325,169.890343,667.652213,-19.318116,0.000000
757,554.000000,913.820158,414.861100,625.241890,-21.700079,0.000000
758,443.000000,793.012191,607.401901,530.225512,-21.815336,-0.109309
759,284.000000,607.800366,702.283681,383.029266,-22.396291,-0.078837
760,103.000000,348.356547,598.045623,194.131265,-23.091088,0.000000
761,3.000000,1.800000,1.800000,1.090585,-25.644371,0.000000
762,0.000000,0.000000,0.000000,0.000000,-26.115605,0.000000
763,0.000000,0.000000,0.000000,0.000000,-26.811674,0.000000
764,0.000000,0.000000,0.000000,0.000000,-28.140965,0.000000
765,0.000000,0.000000,0.000000,0.000000,-29.260291,0.000000
766,0.000000,0.000000,0.000000,0.000000,-29.416416,0.134900
767,0.000000,0.000000,0.000000,0.000000,-29.004085,0.354227

In [7]:
# 14-JUL
day_df= pd.DataFrame()
intervalo = ["2001-07-14","2001-07-15"]
aux = pro.component("roof_wall").variable_dataframe(interval=intervalo)
day_df["Hor. rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("south_wall").variable_dataframe(interval=intervalo)
day_df["South rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux = pro.component("west_wall").variable_dataframe(interval=intervalo)
day_df["West rad. (W/m²)"] = aux["E_dir"] +  aux["E_dif"]
aux =  pro.component("south_window_1").variable_dataframe(interval=intervalo)
day_df["Window trans. rad. (W/m²)"] = aux["E_dir_tra"] +  aux["E_dif_tra"]
aux =  pro.component("Denver").variable_dataframe(interval=intervalo)
day_df["Sky temp. (ºC)"] = aux["sky_temperature"]
aux =  pro.component("system").variable_dataframe(interval=intervalo)
day_df["Load (kWh)"] = aux["Q_sensible"]/1000
day_df.to_clipboard()
day_df

,Hor. rad. (W/m²),South rad. (W/m²),West rad. (W/m²),Window trans. rad. (W/m²),Sky temp. (ºC),Load (kWh)
4656,0.0,0.000000,0.000000,0.000000,4.128365,-0.035624
4657,0.0,0.000000,0.000000,0.000000,3.648777,0.000000
4658,0.0,0.000000,0.000000,0.000000,2.514234,0.000000
4659,0.0,0.000000,0.000000,0.000000,1.463941,0.000000
4660,2.0,1.200000,1.200000,0.727057,0.321597,0.000000
4661,90.0,20.500000,20.500000,12.420551,2.948471,0.000000
4662,275.0,46.000000,46.000000,27.870505,5.535130,0.000000
4663,479.0,73.400000,73.400000,44.471632,7.321400,0.000000
4664,668.0,169.603829,98.800000,70.231291,9.174255,-0.167326
4665,827.0,299.552804,119.200000,119.665913,12.000253,-0.529175
4666,941.0,394.315790,133.600000,172.009090,13.092097,-0.891075
4667,1003.0,445.367964,141.300000,205.034298,13.373687,-1.189123
4668,1008.0,449.285733,236.945012,207.623861,14.259543,-1.429981
4669,955.0,405.619764,473.472680,178.894981,14.504961,-1.558365
4670,848.0,317.091962,671.254933,128.337804,15.304747,-1.554679
4671,696.0,191.665710,808.452844,76.483743,14.504961,-1.435493
4672,509.0,77.400000,861.826785,46.895155,14.652104,-1.316691
4673,306.0,50.100000,808.257445,30.354616,13.053418,-1.170042
4674,114.0,23.900000,592.811027,14.480545,11.825351,-1.010052
4675,5.0,3.000000,3.000000,1.817642,11.273864,-0.829667
4676,0.0,0.000000,0.000000,0.000000,8.187216,-0.676724
4677,0.0,0.000000,0.000000,0.000000,7.703522,-0.571888
4678,0.0,0.000000,0.000000,0.000000,6.814796,-0.459282
4679,0.0,0.000000,0.000000,0.000000,5.464789,-0.333022