In [1]:
import OpenSimula as osm
import numpy as np

alfa = 0.6

bestest_building_600 = {
    "name": "Bestest Building",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "components": [
        # MET_FILE
        {
            "type": "File_met",
            "name": "drycold",
            "file_name": "met_files/DRYCOLD.met"
        },
        # CONSTRUCTION
        {
            "type": "Material",
            "name": "Enlucido",
            "conductivity": 0.16,
            "density": 950,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Aislamiento",
            "conductivity": 0.04,
            "density": 12,
            "specific_heat": 840
        },
        {
            "type": "Material",
            "name": "Madera pared",
            "conductivity": 0.14,
            "density": 530,
            "specific_heat": 900
        },
        {
            "type": "Material",
            "name": "Aislamiento suelo",
            "conductivity": 0.04,
            "density": .1,
            "specific_heat": .1,
        },
        {
            "type": "Material",
            "name": "Madera suelo",
            "conductivity": 0.14,
            "density": 650,
            "specific_heat": 1200,
        },
        {
            "type": "Material",
            "name": "Lecho_rocas",
            "conductivity": 0.14,
            "density": 650,
            "specific_heat": 1200,
        },
        {
            "type": "Construction",
            "name": "Pared 600",
            "solar_absortivity": [alfa, alfa],
            "materials": ["Enlucido", "Aislamiento", "Madera pared"],
            "thicknesses": [0.12, 0.066, 0.009],
        },
        {
            "type": "Construction",
            "name": "Suelo 600",
            "solar_absortivity": [alfa, alfa],
            "materials": ["Aislamiento suelo", "Madera suelo"],
            "thicknesses": [1.003, 0.025],
        },
        {
            "type": "Construction",
            "name": "Techo 600",
            "solar_absortivity": [alfa, alfa],
            "materials": ["Enlucido", "Aislamiento", "Madera pared"],
            "thicknesses": [0.010, 0.01118, 0.019],
        },
        {
            "type": "Window",
            "name": "Vidrio doble",
            "solar_absortivity": [0.13, 0.13],
            "solar_transmisivity": [0.66, 0.66],
            "R_glazing": 0.921,
            "R_frame": 0.921,
            "frame_fraction": 0
        },
        # BUILDING
        {
            "type": "Building",
            "name": "Bestest 600",
            "file_met": "drycold"
        },
        {
            "type": "Space_type",
            "name": "bestest space",
            "aux_variables": [],
            "people_density": "0",
            "light_density": "0",
            "other_gains_density": "4.1667",
            "other_gains_radiant_fraction": 0.6,
            "infiltration": "0.5"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Bestest 600",
            "space_type": "bestest space",
            "floor_area": 48,
            "volume": 48*2.7,
        },
        # Surfaces
        {
            "type": "Surface",
            "name": "north_wall",
            "location": "EXTERIOR",
            "virtual": False,
            "construction": "Pared 600",
            "space": "space_1",
            "area": 8*2.7,
            "azimuth": 180,
            "altitude": 0
        },
        {
            "type": "Surface",
            "name": "east_wall",
            "location": "EXTERIOR",
            "construction": "Pared 600",
            "space": "space_1",
            "area": 6*2.7,
            "azimuth": 90,
            "altitude": 0
        },
        {
            "type": "Surface",
            "name": "south_wall",
            "location": "EXTERIOR",
            "construction": "Pared 600",
            "space": "space_1",
            "area": 8*2.7,
            "azimuth": 0,
            "altitude": 0
        },
        {
            "type": "Opening",
            "name": "south_window_1",
            "surface": "south_wall",
            "window": "Vidrio doble",
            "width": 3,
            "height": 2,
        },
        {
            "type": "Opening",
            "name": "south_window_2",
            "surface": "south_wall",
            "window": "Vidrio doble",
            "width": 3,
            "height": 2,
        },
        {
            "type": "Surface",
            "name": "west_wall",
            "location": "EXTERIOR",
            "construction": "Pared 600",
            "space": "space_1",
            "area": 6*2.7,
            "azimuth": -90,
            "altitude": 0
        },
        {
            "type": "Surface",
            "name": "roof",
            "location": "EXTERIOR",
            "construction": "Techo 600",
            "space": "space_1",
            "area": 8*6,
            "azimuth": 0,
            "altitude": 90
        },
        {
            "type": "Surface",
            "name": "floor",
            "location": "UNDERGROUND",
            "construction": "Suelo 600",
            "space": "space_1",
            "area": 8*6,
            "azimuth": 0,
            "altitude": -90
        },
    ],
}

In [2]:
sim = osm.Simulation()
pro = osm.Project("pro", sim)
pro.read_dict(bestest_building_600)
pro.simulate()
ktemp = pro.component("Bestest 600")._KTEMP_matrix
T = np.array([20,20,20,20,20,20,20,20]).transpose()
Q_temp = ktemp.dot(T)
Q_temp

Reading project data from dictonary
Reading completed.
Checking project: Bestest Building
ok
Simulating Bestest Building: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End

array([0.01207058, 0.00868631, 0.0053647 , 0.00335294, 0.00335294,
       0.00868631, 0.39591599, 0.39591599])

In [3]:
pro.component("south_wall").variable_dataframe().head(20)

                  date  T_s1 [°C]  T_s2 [°C]  solar_direct_rad [W/m²]
0  2001-01-01 00:00:00        0.0        0.0                 0.000000
1  2001-01-01 01:00:00        0.0        0.0                 0.000000
2  2001-01-01 02:00:00        0.0        0.0                 0.000000
3  2001-01-01 03:00:00        0.0        0.0                 0.000000
4  2001-01-01 04:00:00        0.0        0.0                 0.000000
5  2001-01-01 05:00:00        0.0        0.0                 0.000000
6  2001-01-01 06:00:00        0.0        0.0                 0.000000
7  2001-01-01 07:00:00        0.0        0.0                 0.000000
8  2001-01-01 08:00:00        0.0        0.0                -3.310295
9  2001-01-01 09:00:00        0.0        0.0                -6.538573
10 2001-01-01 10:00:00        0.0        0.0              -121.897261
11 2001-01-01 11:00:00        0.0        0.0              -342.967021
12 2001-01-01 12:00:00        0.0        0.0              -423.139384
13 2001-01-01 13:00:00        0.0        0.0              -390.205995
14 2001-01-01 14:00:00        0.0        0.0              -282.371095
15 2001-01-01 15:00:00        0.0        0.0              -145.861932
16 2001-01-01 16:00:00        0.0        0.0               -40.334727
17 2001-01-01 17:00:00        0.0        0.0                -0.920959
18 2001-01-01 18:00:00        0.0        0.0                 0.000000
19 2001-01-01 19:00:00        0.0        0.0                 0.000000

In [4]:
pro.component("drycold").variable_dataframe().head(20)

,date,sol_hour [h],temperature [°C],sky_temperature [°C],rel_humidity [%],sol_direct [W/m²],sol_diffuse [W/m²],wind_speed [m/s],wind_direction [°],sol_azimuth [°],sol_altitude [°]
0,2001-01-01 00:00:00,-0.04174,-0.379218,-0.379218,42.993969,0.000000,0.000000,2.420782,152.618145,0.000000,0.000000
1,2001-01-01 01:00:00,0.95826,0.000000,0.000000,57.845650,0.000000,0.000000,3.029130,203.000000,0.000000,0.000000
2,2001-01-01 02:00:00,1.95826,0.000000,0.000000,57.825222,0.000000,0.000000,3.483304,192.460029,0.000000,0.000000
3,2001-01-01 03:00:00,2.95826,0.000000,0.000000,56.200001,0.000000,0.000000,3.883304,180.000000,0.000000,0.000000
4,2001-01-01 04:00:00,3.95826,0.000000,0.000000,56.429131,0.000000,0.000000,4.329130,190.539971,0.000000,0.000000
5,2001-01-01 05:00:00,4.95826,0.000000,0.000000,51.979927,0.000000,0.000000,4.783304,244.243366,0.000000,0.000000
6,2001-01-01 06:00:00,5.95826,1.512257,1.512257,45.483483,0.000000,0.000000,4.129307,303.081712,0.000000,0.000000
7,2001-01-01 07:00:00,6.95826,2.795914,2.795914,47.195385,0.000000,3.161991,3.558260,232.513267,0.000000,0.000000
8,2001-01-01 08:00:00,7.95826,2.704086,2.704086,50.866607,5.590767,40.902863,3.641740,104.296605,53.693812,5.545160
9,2001-01-01 09:00:00,8.95826,5.087213,5.087213,40.576724,8.900531,95.076917,6.170339,191.730099,42.724267,14.140744
10,2001-01-01 10:00:00,9.95826,7.474956,7.474956,25.654528,140.965637,85.616679,10.029130,317.378317,30.148073,20.994433
11,2001-01-01 11:00:00,10.95826,8.304086,8.304086,23.870693,356.691167,49.859146,9.841740,293.000000,15.945442,25.517138
12,2001-01-01 12:00:00,11.95826,9.129130,9.129130,24.487566,423.166435,43.900002,9.300000,303.081712,0.647852,27.185644
13,2001-01-01 13:00:00,12.95826,9.949912,9.949912,21.754528,403.407620,45.091476,9.300000,304.918288,-14.698426,25.771359
14,2001-01-01 14:00:00,13.95826,10.325044,10.325044,19.466608,322.917187,47.462344,7.146180,303.081712,-29.021454,21.469416
15,2001-01-01 15:00:00,14.95826,9.725044,9.725044,21.320605,195.476686,48.920780,6.524690,294.378317,-41.738946,14.787372
16,2001-01-01 16:00:00,15.95826,8.162699,8.162699,23.366607,66.763020,35.735515,8.295914,156.809872,-52.832463,6.316141
17,2001-01-01 17:00:00,16.95826,6.195914,6.195914,24.029129,0.920959,10.672286,6.279395,43.621683,0.000000,0.000000
18,2001-01-01 18:00:00,17.95826,4.316873,4.316873,28.928423,0.000000,0.000000,3.179395,88.621683,0.000000,0.000000
19,2001-01-01 19:00:00,18.95826,2.525044,2.525044,35.087391,0.000000,0.000000,2.233215,113.000000,0.000000,0.000000