In [10]:
import OpenSimula as oms

p1_dic = {
    "name": "project 1",
    "components": [
        {
            "type": "Test_component",
            "name": "comp 1",
            "boolean": True,
            "string": "Hola mundo",
            "int": 24,
            "float": 34.5,
            "options": "Two",
            "boolean_list": [True, True],
            "string_list": ["Hola 1", "Hola 2"],
            "int_list": [1, 2],
            "float_list": [1.1, 2.1],
            "options_list": ["Two", "Two"],
        },
        {
            "type": "Test_component",
            "name": "comp 2",
            "boolean": True,
            "string": "Hola mundo",
            "int": 24,
            "float": 34.6,
            "options": "Two",
            "component": "comp 1",
            "variable": "t_1 = comp 1.t"
        },
    ],
}

p2_dic = {
    "name": "project 2",
    "components": [
        {
            "type": "Test_component",
            "name": "comp 3",
            "component": "project 1->comp 1",
            "component_list": ["project 1->comp 1", "project 1->comp 2"],
            "variable": "t_1 = project 1->comp 1.t",
            "variable_list": ["t_2 = project 1->comp 1.t","t_3 = project 1->comp 2.t"],
            "math_exp": "4 * t_1 ",
            "math_exp_list": ["6 * t_2 ","ln(23)"]
        }
    ],
}

In [11]:

sim = oms.Simulation()
p1 = oms.Project("p1",sim)
p1.read_dict(p1_dic)
sim

Reading project data from dictonary
Reading completed.
Checking project: project 1
ok

In [12]:
p1

In [13]:
p1.simulate()
p1.component("comp 1")

Component: comp 1 Starting simulation ...
Component: comp 2 Starting simulation ...
Simulating project 1: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End
Component: comp 1 Ending simulation ...
Component: comp 2 Ending simulation ...

In [14]:
p1.component("comp 2")

In [15]:
p2 = oms.Project("p2",sim)
p2.read_dict(p2_dic)
p2

Reading project data from dictonary
Reading completed.
Checking project: project 2
ok

In [16]:
p2.simulate()

Component: comp 1 Starting simulation ...
Component: comp 2 Starting simulation ...
Component: comp 3 Starting simulation ...
Simulating project 2: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End
Component: comp 1 Ending simulation ...
Component: comp 2 Ending simulation ...
Component: comp 3 Ending simulation ...

In [17]:
p2.component("comp 3")

In [18]:
sim.message_list()

['Reading project data from dictonary',
 'Reading completed.',
 'Checking project: project 1',
 'ok',
 'Component: comp 1 Starting simulation ...',
 'Component: comp 2 Starting simulation ...',
 'Simulating project 1: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End',
 'Component: comp 1 Ending simulation ...',
 'Component: comp 2 Ending simulation ...',
 'Reading project data from dictonary',
 'Reading completed.',
 'Checking project: project 2',
 'ok',
 'Component: comp 1 Starting simulation ...',
 'Component: comp 2 Starting simulation ...',
 'Component: comp 3 Starting simulation ...',
 'Simulating project 2: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%  End',
 'Component: comp 1 Ending simulation ...',
 'Component: comp 2 Ending simulation ...',
 'Component: comp 3 Ending simulation ...']