## ASHRAE 140-2023

Section 9: CASE CE545 - Dry Coil, Increased Thermostat Set Point (EDB Sensitivity)

In [ ]:
import OpenSimula as osm
import pandas as pd
import numpy as np

case_ce545_dict = {
    "name": "Case CE545",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "simulation_file_met": "meteo",
    "components": [ 
        {
            "type": "File_met",
            "name": "meteo",
            "file_type": "TMY2",
            "file_name": "../../mets/CE300.TM2"
        },    
        {
            "type": "Material",
            "name": "Insulation",
            "conductivity": 0.00308,
            "density": 1,
            "specific_heat": 1
        },
        {
            "type": "Construction",
            "name": "Adiabatic_Wall",
            "solar_alpha": [0.1,0.6],
            "lw_epsilon": [0.9,0.9],
            "materials": [
                "Insulation"
            ],
            "thicknesses": [
                1.0
            ]
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_1",
            "time_steps": [8*3600, 12*3600],
            "values": [0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_2",
            "time_steps": [9*3600, 9*3600],
            "values": [0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_3",
            "time_steps": [8*3600, 11*3600],
            "values": [0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_4",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0, 0, 0, 0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_5",
            "time_steps": [8*3600, 8*3600],
            "values": [0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_6",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0, 0, 0, 0, 0, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_1",
            "time_steps": [],
            "values": [0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_2",
            "time_steps": [9*3600, 9*3600],
            "values": [0, 0.375, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_3",
            "time_steps": [8*3600, 11*3600],
            "values": [0, 0.5, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_4",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0.375, 0.5, 0.75, 1, 0.5, 0.375],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_5",
            "time_steps": [8*3600, 8*3600],
            "values": [0, 0.5, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_6",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0, 0.5, 0.75, 1, 0.5, 0.375],
            "interpolation": "STEP",
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_1",
            "days_schedules": ["latent_day_1"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_2",
            "days_schedules": ["latent_day_2"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_3",
            "days_schedules": ["latent_day_3"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_4",
            "days_schedules": ["latent_day_4"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_5",
            "days_schedules": ["latent_day_5"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_6",
            "days_schedules": ["latent_day_6"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_1",
            "days_schedules": ["sensible_day_1"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_2",
            "days_schedules": ["sensible_day_2"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_3",
            "days_schedules": ["sensible_day_3"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_4",
            "days_schedules": ["sensible_day_4"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_5",
            "days_schedules": ["sensible_day_5"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_6",
            "days_schedules": ["sensible_day_6"],
        },
        {
            "type": "Year_schedule",
            "name": "latent_schedule",
            "periods": ["10/03", "10/04","11/04","20/04","12/10","18/10","05/11"],
            "weeks_schedules": ["latent_week_1"
                                , "latent_week_2"
                                , "latent_week_1"
                                , "latent_week_3"
                                , "latent_week_4"
                                , "latent_week_5"
                                , "latent_week_6"
                                , "latent_week_1"],
        },
        {
            "type": "Year_schedule",
            "name": "sensible_schedule",
            "periods": ["10/03", "10/04","11/04","20/04","12/10","18/10","05/11"],
            "weeks_schedules": ["sensible_week_1"
                                , "sensible_week_2"
                                , "sensible_week_1"
                                , "sensible_week_3"
                                , "sensible_week_4"
                                , "sensible_week_5"
                                , "sensible_week_6"
                                , "sensible_week_1"],
        },
        {
            "type": "Space_type",
            "name": "space_gains",
            "input_variables": ["f_l = latent_schedule.values","f_s = sensible_schedule.values"],
            "people_density": "f_l",
            "people_sensible": 0,
            "people_latent": 38.883,            
            "light_density": "0",
            "other_gains_density": "95.704*f_s",
            "other_gains_radiant_fraction": 0,
            "infiltration": "0"
        },
        {
            "type": "Building",
            "name": "Building",
            "albedo": 0.2,
            "azimuth": 0,
            "shadow_calculation": "INSTANT"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Building",
            "space_type": "space_gains",
            "floor_area": 196,
            "volume": 588,
            "furniture_weight": 0
        },
        {
            "type": "Exterior_surface",
            "name": "north_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                14,
                14,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 180,
            "altitude": 0,
            "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "east_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                14,
                0,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "south_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 0,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "west_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                14,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": -90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "roof_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                3
            ],
            "width": 14,
            "height": 14,
            "azimuth": 0,
            "altitude": 90,
            "h_cv": [
                24.17,
                1.0
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "floor_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                14,
                0
            ],
            "width": 14,
            "height": 14,
            "azimuth": 0,
            "altitude": -90,
            "h_cv": [
                24.17,
                4.13
            ]
        },
        {
            "type": "HVAC_DX_equipment",
            "name": "HVAC_equipment",
            "nominal_air_flow": 1.888,
            "nominal_total_cooling_capacity": 33277,
            "nominal_sensible_cooling_capacity": 26043,
            "nominal_cooling_power": 10937,
            "indoor_fan_power": 1242,
            "indoor_fan_operation": "CYCLING",      
            "nominal_cooling_conditions": [26.67,19.44,35],            
            "total_cooling_capacity_expression": "-3.762e-03 * T_odb + 1.941e-02 * T_iwb + 4.783e-03 * T_idb -2.535e-05 * T_odb**2 + 1.232e-03 * T_iwb**2 + 4.448e-04 * T_idb**2 -2.754e-04 * T_odb * T_iwb + 5.977e-05 * T_odb * T_idb -1.297e-03 * T_iwb * T_idb + 6.851e-01",
            "sensible_cooling_capacity_expression": "-4.491e-03*T_odb -3.135e-02*T_iwb -1.011e-01*T_idb -6.467e-05*T_odb**2 -4.991e-03*T_iwb**2 +6.132e-03*T_idb**2 +3.255e-04*T_odb*T_iwb -1.873e-04*T_odb*T_idb +4.163e-03*T_iwb*T_idb +4.984e-07*T_odb**3 +3.308e-05*T_iwb**3 -1.075e-04*T_idb**3 + 1.6552",            
            "cooling_power_expression": "7.990e-03 * T_odb +6.779e-05 * T_iwb + 5.339e-04 * T_idb -2.125e-05 * T_odb**2 +4.948e-04 * T_iwb**2 +1.983e-04 * T_idb**2 + 1.931e-04 * T_odb * T_iwb +7.733e-05 * T_odb * T_idb -5.698e-04 * T_iwb * T_idb + 4.978e-01",
            "EER_expression": "1 - 0.229*(1-F_load)",
            "expression_max_values": [40,35,50,30,1.5,1]
        },
        {
            "type": "HVAC_DX_system",
            "name": "system",
            "space": "space_1",
            "equipment": "HVAC_equipment",
            "supply_air_flow": 1.888,
            "outdoor_air_flow": 0,
            "heating_setpoint": "15",
            "cooling_setpoint": "35",
            "system_on_off": "1",
            "control_type": "TEMPERATURE"
        }
    ]
}


sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_dict(case_ce545_dict)
pro.simulate(5)

Reading project data from dictonary
Reading completed.
Checking project: Case CE545
ok
Calculating solar direct shadows ...
Calculating solar diffuse shadows ...
Simulating Case CE545: ...
5%: N_iter: 122.71
10%: N_iter: 1.82
15%: N_iter: 1.85
20%: N_iter: 2.08
25%: N_iter: 2.75
30%: N_iter: 2.85
35%: N_iter: 4.18
40%: N_iter: 4.16
45%: N_iter: 4.16
50%: N_iter: 4.16
55%: N_iter: 4.17
60%: N_iter: 4.16
65%: N_iter: 4.16
70%: N_iter: 4.16
75%: N_iter: 4.17
80%: N_iter: 3.61
85%: N_iter: 3.32
90%: N_iter: 1.91
95%: N_iter: 1.81
100%: N_iter: 1.84
Simulation completed.

In [2]:
system = pro.component("system")
sys_df=system.variable_dataframe()
sys_df["time_frac"] = -sys_df["F_load"]/sys_df["efficiency_degradation"]
sys_df["power_vi"] = sys_df["time_frac"]*1242
sys_df["power_ve"] = sys_df["time_frac"]*930
sys_df["power_comp"] = sys_df["power"]-sys_df["power_vi"]-sys_df["power_ve"] 
sys_df["Q_total"] = sys_df["Q_sensible"]+sys_df["Q_latent"]
sys_df["COP2"] = -sys_df["Q_total"] / (sys_df["power_comp"] + sys_df["power_ve"])

In [3]:
df_sum = sys_df.resample("Y", on='date').sum()
excel = pd.DataFrame()
excel["Total_consumption"] = [df_sum["power"][0]/1000]
excel["Compressor_consumption"] = [df_sum["power_comp"][0]/1000]
excel["Outdoor_fan_consumption"] = [df_sum["power_ve"][0]/1000]
excel["Indoor_fan_consumption"] = [df_sum["power_vi"][0]/1000]
excel["Q_total"] = [-df_sum["Q_total"][0]/1000]
excel["Q_sensible"] = [-df_sum["Q_sensible"][0]/1000]
excel["Q_latent"] = [-df_sum["Q_latent"][0]/1000]
excel["COP2_mean"] = -df_sum["Q_total"][0]/(df_sum["power_comp"][0]+df_sum["power_ve"][0])
df_space_mean = pro.component("space_1").variable_dataframe(frequency="Y",value="mean")
excel["T_space_mean"] = [df_space_mean["temperature"][0]]
excel["w_space_mean"] = [df_space_mean["abs_humidity"][0]/1000]
excel["HR_space_mean"] = [df_space_mean["rel_humidity"][0]]

excel.to_clipboard()
excel

,Total_consumption,Compressor_consumption,Outdoor_fan_consumption,Indoor_fan_consumption,Q_total,Q_sensible,Q_latent,COP2_mean,T_space_mean,w_space_mean,HR_space_mean
0,16305.574436,13150.080111,1351.109448,1804.384876,47105.162359,47105.162359,-0.0,3.248365,26.61834,0.005684,35.17314

In [4]:
excel_max = pd.DataFrame()
excel_max["max_power"] = [sys_df["power"].max()]
excel_max["max_power_day"] = [pro.dates()[sys_df['power'].idxmax()].strftime("%d-%b")]
excel_max["max_power_hour"] = [int(pro.dates()[sys_df['power'].idxmax()].strftime("%H"))+1]
excel_max["max_Q_sen"] = [-sys_df["Q_sensible"].min()]
excel_max["max_Q_sen_day"] = [pro.dates()[sys_df['Q_sensible'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_sen_hour"] = [int(pro.dates()[sys_df['Q_sensible'].idxmin()].strftime("%H"))+1]
excel_max["max_Q_lat"] = [-sys_df["Q_latent"].min()]
excel_max["max_Q_lat_day"] = [pro.dates()[sys_df['Q_latent'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_lat_hour"] = [int(pro.dates()[sys_df['Q_latent'].idxmin()].strftime("%H"))+1]
excel_max["max_Q_tot"] = [-sys_df["Q_total"].min()]
excel_max["max_Q_tot_day"] = [pro.dates()[sys_df['Q_total'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_tot_hour"] = [int(pro.dates()[sys_df['Q_total'].idxmin()].strftime("%H"))+1]

excel_max.to_clipboard()
excel_max

,max_power,max_power_day,max_power_hour,max_Q_sen,max_Q_sen_day,max_Q_sen_hour,max_Q_lat,max_Q_lat_day,max_Q_lat_hour,max_Q_tot,max_Q_tot_day,max_Q_tot_hour
0,7419.679725,20-Jul,15,19394.227377,04-Jun,16,0.0,01-Jan,1,19394.227377,04-Jun,16

In [5]:
excel_max_2 = pd.DataFrame()
excel_max_2["max_COP2"] = [sys_df["COP2"].max()]
excel_max_2["max_COP2_day"] = [pro.dates()[sys_df['COP2'].idxmax()].strftime("%d-%b")]
excel_max_2["max_COP2_hour"] = [int(pro.dates()[sys_df['COP2'].idxmax()].strftime("%H"))+1]
excel_max_2["min_COP2"] = [sys_df["COP2"].min()]
excel_max_2["min_COP2_day"] = [pro.dates()[sys_df['COP2'].idxmin()].strftime("%d-%b")]
excel_max_2["min_COP2_hour"] = [int(pro.dates()[sys_df['COP2'].idxmin()].strftime("%H"))+1]
space_df = pro.component("space_1").variable_dataframe()
excel_max_2["max_T_spa"] = [space_df["temperature"].max()]
excel_max_2["max_T_spa_day"] = [pro.dates()[space_df['temperature'].idxmax()].strftime("%d-%b")]
excel_max_2["max_T_spa_hour"] = [int(pro.dates()[space_df['temperature'].idxmax()].strftime("%H"))+1]
excel_max_2["min_T_spa"] = [space_df["temperature"].min()]
excel_max_2["min_T_spa_day"] = [pro.dates()[space_df['temperature'].idxmin()].strftime("%d-%b")]
excel_max_2["min_T_spa_hour"] = [int(pro.dates()[space_df['temperature'].idxmin()].strftime("%H"))+1]
excel_max_2["max_w_spa"] = [space_df["abs_humidity"].max()/1000]
excel_max_2["max_w_spa_day"] = [pro.dates()[space_df['abs_humidity'].idxmax()].strftime("%d-%b")]
excel_max_2["max_w_spa_hour"] = [int(pro.dates()[space_df['abs_humidity'].idxmax()].strftime("%H"))+1]
excel_max_2["min_w_spa"] = [space_df["abs_humidity"].min()/1000]
excel_max_2["min_w_spa_day"] = [pro.dates()[space_df['abs_humidity'].idxmin()].strftime("%d-%b")]
excel_max_2["min_w_spa_hour"] = [int(pro.dates()[space_df['abs_humidity'].idxmin()].strftime("%H"))+1]
excel_max_2["max_hr_spa"] = [space_df["rel_humidity"].max()]
excel_max_2["max_hr_spa_day"] = [pro.dates()[space_df['rel_humidity'].idxmax()].strftime("%d-%b")]
excel_max_2["max_hr_spa_hour"] = [int(pro.dates()[space_df['rel_humidity'].idxmax()].strftime("%H"))+1]
excel_max_2["min_hr_spa"] = [space_df["rel_humidity"].min()]
excel_max_2["min_hr_spa_day"] = [pro.dates()[space_df['rel_humidity'].idxmin()].strftime("%d-%b")]
excel_max_2["min_hr_spa_hour"] = [int(pro.dates()[space_df['rel_humidity'].idxmin()].strftime("%H"))+1]

excel_max_2.to_clipboard()
excel_max_2

,max_COP2,max_COP2_day,max_COP2_hour,min_COP2,min_COP2_day,min_COP2_hour,max_T_spa,max_T_spa_day,max_T_spa_hour,min_T_spa,...,max_w_spa_hour,min_w_spa,min_w_spa_day,min_w_spa_hour,max_hr_spa,max_hr_spa_day,max_hr_spa_hour,min_hr_spa,min_hr_spa_day,min_hr_spa_hour
0,4.427932,11-Apr,19,2.76199,29-Jul,12,35.023436,20-Jul,15,5.621822,...,1,0.005645,02-Nov,14,100.0,06-Jan,8,16.167498,20-Jul,16

In [11]:
sim_df = pro.simulation_dataframe()
sim_df.loc[sim_df['n_iterations'] > 10]

                  dates  n_iterations last_component
113 2001-01-05 17:30:00          1000        space_1
114 2001-01-05 18:30:00          1000        space_1
115 2001-01-05 19:30:00          1000        space_1
116 2001-01-05 20:30:00          1000        space_1
117 2001-01-05 21:30:00          1000        space_1
118 2001-01-05 22:30:00          1000        space_1
119 2001-01-05 23:30:00          1000        space_1
120 2001-01-06 00:30:00          1000        space_1
121 2001-01-06 01:30:00          1000        space_1
122 2001-01-06 02:30:00          1000        space_1
123 2001-01-06 03:30:00          1000        space_1
124 2001-01-06 04:30:00          1000        space_1
125 2001-01-06 05:30:00          1000        space_1
126 2001-01-06 06:30:00          1000        space_1
127 2001-01-06 07:30:00          1000        space_1
128 2001-01-06 08:30:00          1000        space_1
151 2001-01-07 07:30:00          1000        space_1
257 2001-01-11 17:30:00          1000        space_1
258 2001-01-11 18:30:00          1000        space_1
259 2001-01-11 19:30:00          1000        space_1
260 2001-01-11 20:30:00          1000        space_1
261 2001-01-11 21:30:00          1000        space_1
262 2001-01-11 22:30:00          1000        space_1
263 2001-01-11 23:30:00          1000        space_1
264 2001-01-12 00:30:00          1000        space_1
265 2001-01-12 01:30:00          1000        space_1
266 2001-01-12 02:30:00          1000        space_1
267 2001-01-12 03:30:00          1000        space_1
268 2001-01-12 04:30:00          1000        space_1
269 2001-01-12 05:30:00          1000        space_1
270 2001-01-12 06:30:00          1000        space_1
271 2001-01-12 07:30:00          1000        space_1
272 2001-01-12 08:30:00          1000        space_1
273 2001-01-12 09:30:00          1000        space_1
274 2001-01-12 10:30:00          1000        space_1
282 2001-01-12 18:30:00          1000        space_1
283 2001-01-12 19:30:00          1000        space_1
284 2001-01-12 20:30:00          1000        space_1
285 2001-01-12 21:30:00          1000        space_1
286 2001-01-12 22:30:00          1000        space_1
287 2001-01-12 23:30:00          1000        space_1
288 2001-01-13 00:30:00          1000        space_1
289 2001-01-13 01:30:00          1000        space_1
290 2001-01-13 02:30:00          1000        space_1
291 2001-01-13 03:30:00          1000        space_1
292 2001-01-13 04:30:00          1000        space_1
293 2001-01-13 05:30:00          1000        space_1
294 2001-01-13 06:30:00          1000        space_1
295 2001-01-13 07:30:00          1000        space_1
316 2001-01-14 04:30:00          1000        space_1
317 2001-01-14 05:30:00          1000        space_1
318 2001-01-14 06:30:00          1000        space_1
319 2001-01-14 07:30:00          1000        space_1