## ASHRAE 140-2023

Section 9: CASE CE200 - Full load test at AHRI conditions

In [1]:
import OpenSimula as osm
import pandas as pd
import numpy as np

case_ce200_dict = {
    "name": "Case CE200",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "components": [
        {
            "type": "File_met",
            "name": "T_ext_cte",
            "file_type": "TMY2",
            "file_name": "../../mets/CE200A.TM2"
        },    
        {
            "type": "Material",
            "name": "Insulation",
            "conductivity": 0.01,
            "density": 1,
            "specific_heat": 1
        },
        {
            "type": "Construction",
            "name": "Adiabatic_Wall",
            "solar_alpha": [0.1,0.6],
            "lw_epsilon": [0.9,0.9],
            "materials": [
                "Insulation"
            ],
            "thicknesses": [
                1.0
            ]
        },
        {
            "type": "Space_type",
            "name": "constant_gain_space",
            "people_density": "0",
            "light_density": "0",
            "other_gains_density": "165.35",
            "other_gains_radiant_fraction": 0,
            "other_gains_latent_fraction": 0.22893,
            "infiltration": "0"
        },
        {
            "type": "Building",
            "name": "Building",
            "file_met": "T_ext_cte",
            "albedo": 0.2,
            "azimuth": 0,
            "shadow_calculation": "INSTANT"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Building",
            "space_type": "constant_gain_space",
            "floor_area": 48,
            "volume": 129.6,
            "furniture_weight": 0
        },
        {
            "type": "Exterior_surface",
            "name": "north_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                8,
                6,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 180,
            "altitude": 0,
            "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "east_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                8,
                0,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": 90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "south_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                0
            ],
            "width": 8,
            "height": 2.7,
            "azimuth": 0,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "west_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 6,
            "height": 2.7,
            "azimuth": -90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "roof_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                2.7
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": 90,
            "h_cv": [
                24.17,
                1.0
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "floor_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                6,
                0
            ],
            "width": 8,
            "height": 6,
            "azimuth": 0,
            "altitude": -90,
            "h_cv": [
                24.17,
                4.13
            ]
        },
        {
            "type": "HVAC_DX_equipment",
            "name": "HVAC_equipment",
            "nominal_air_flow": 0.4248,
            "nominal_total_cooling_capacity": 7951,
            "nominal_sensible_cooling_capacity": 6136,
            "nominal_cooling_power": 2198,
            "no_load_power": 0,
            "nominal_cooling_conditions": [26.7,19.4,35],
            "total_cooling_capacity_expression": "9.099e-04 * T_odb + 4.351e-02 * T_iwb -3.475e-05 * T_odb**2 + 1.512e-04 * T_iwb**2 -4.703e-04 * T_odb * T_iwb + 4.281e-01",
            "sensible_cooling_capacity_expression": "1.148e-03 * T_odb - 7.886e-02 * T_iwb + 1.044e-01 * T_idb - 4.117e-05 * T_odb**2 - 3.917e-03 * T_iwb**2 - 2.450e-03 * T_idb**2 + 4.042e-04 * T_odb * T_iwb - 4.762e-04 * T_odb * T_idb + 5.503e-03 * T_iwb * T_idb  + 2.903e-01",
            "cooling_power_expression": "1.198e-02 * T_odb + 1.432e-02 * T_iwb + 5.656e-05 * T_odb**2 + 3.725e-05 * T_iwb**2 - 1.840e-04 * T_odb * T_iwb + 3.454e-01",
            "EER_expression": "1 - 0.229*(1-F_load)",
            "expression_max_values": [40,30,50,30,1,1]
        },
        {
            "type": "HVAC_DX_system",
            "name": "system",
            "space": "space_1",
            "file_met": "T_ext_cte",
            "equipment": "HVAC_equipment",
            "supply_air_flow": 0.4248,
            "outdoor_air_flow": 0,
            "heating_setpoint": "20",
            "cooling_setpoint": "26.7",
            "system_on_off": "1",
            "control_type": "PERFECT"
        }
    ]
}


sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_dict(case_ce200_dict)
pro.simulate(5)

Reading project data from dictonary
Reading completed.
Checking project: Case CE200
ok
Calculating solar direct shadows ...
Calculating solar diffuse shadows ...
Simulating Case CE200: ...
5%: N_iter: 41.48
10%: N_iter: 41.60
15%: N_iter: 41.48
20%: N_iter: 41.43
25%: N_iter: 41.43
30%: N_iter: 41.42
35%: N_iter: 41.28
40%: N_iter: 41.28
45%: N_iter: 41.23
50%: N_iter: 41.27
55%: N_iter: 41.33
60%: N_iter: 41.24
65%: N_iter: 41.34
70%: N_iter: 41.29
75%: N_iter: 41.32
80%: N_iter: 41.41
85%: N_iter: 41.49
90%: N_iter: 41.60
95%: N_iter: 41.52
100%: N_iter: 41.78
Simulation completed.

In [2]:
system = pro.component("system")
sys_df=system.variable_dataframe()
sys_df["time_frac"] = -sys_df["F_load"]/sys_df["efficiency_degradation"]
sys_df["power_vi"] = sys_df["time_frac"]*230
sys_df["power_ve"] = sys_df["time_frac"]*108
sys_df["power_comp"] = sys_df["power"]-sys_df["power_vi"]-sys_df["power_ve"]
sys_df["Q_sen_sys"] = sys_df["Q_sensible"]-sys_df["power_vi"] 
sys_df["Q_tot_sys"] = sys_df["Q_sensible"]+sys_df["Q_latent"]-sys_df["power_vi"]

sys_df

,date,state,T_odb,T_owb,T_idb,T_iwb,F_air,F_load,outdoor_air_flow,T_supply,...,cooling_setpoint,EER,COP,efficiency_degradation,time_frac,power_vi,power_ve,power_comp,Q_sen_sys,Q_tot_sys
0,2001-01-01 00:30:00,-1.0,35.0,21.029424,26.782173,19.071952,1.0,-0.929340,0.0,15.390324,...,26.7,3.524748,0.0,0.983819,0.944625,217.263774,102.019512,1752.481109,-6058.133157,-7519.711101
1,2001-01-01 01:30:00,-1.0,35.0,21.029424,26.786847,19.385087,1.0,-0.996472,0.0,14.822380,...,26.7,3.606563,0.0,0.999192,0.997278,229.373826,107.705970,1856.554636,-6363.838299,-8140.854817
2,2001-01-01 02:30:00,-1.0,35.0,21.025538,26.781654,19.427725,1.0,-0.999807,0.0,14.816449,...,26.7,3.612958,0.0,0.999956,0.999851,229.965843,107.983961,1862.220301,-6364.808936,-8179.087888
3,2001-01-01 03:30:00,-2.0,35.0,21.021004,26.783089,19.434616,1.0,-1.000000,0.0,14.820225,...,26.7,3.613705,0.0,1.000000,1.000000,230.000000,108.000000,1862.638180,-6363.642454,-8182.457431
4,2001-01-01 04:30:00,-2.0,35.0,21.025538,26.784715,19.436389,1.0,-1.000000,0.0,14.822093,...,26.7,3.613856,0.0,1.000000,1.000000,230.000000,108.000000,1862.674523,-6363.518617,-8182.921498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2001-12-31 19:30:00,-2.0,35.0,21.054682,26.787510,19.439288,1.0,-1.000000,0.0,14.825180,...,26.7,3.614104,0.0,1.000000,1.000000,230.000000,108.000000,1862.733966,-6363.369144,-8183.680529
8756,2001-12-31 20:30:00,-2.0,35.0,21.058568,26.787526,19.439300,1.0,-1.000000,0.0,14.825193,...,26.7,3.614105,0.0,1.000000,1.000000,230.000000,108.000000,1862.734200,-6363.370399,-8183.683515
8757,2001-12-31 21:30:00,-2.0,35.0,21.058568,26.787523,19.439297,1.0,-1.000000,0.0,14.825190,...,26.7,3.614104,0.0,1.000000,1.000000,230.000000,108.000000,1862.734152,-6363.370050,-8183.682906
8758,2001-12-31 22:30:00,-2.0,35.0,21.054682,26.787523,19.439298,1.0,-1.000000,0.0,14.825191,...,26.7,3.614104,0.0,1.000000,1.000000,230.000000,108.000000,1862.734164,-6363.370128,-8183.683060
8759,2001-12-31 23:30:00,-2.0,35.0,21.054682,26.787354,19.439104,1.0,-1.000000,0.0,14.824989,...,26.7,3.614088,0.0,1.000000,1.000000,230.000000,108.000000,1862.730190,-6363.386761,-8183.632311

In [3]:
mes_df_sum = sys_df.resample("M", on='date').sum()
print("Total consumption: ",mes_df_sum["power"][1]/1000)
print("Compressor consumption: ",mes_df_sum["power_comp"][1]/1000)
print("Indoor fan consumption: ",mes_df_sum["power_vi"][1]/1000)
print("Outdoor fan consumption: ",mes_df_sum["power_ve"][1]/1000)
print("Total coil load: ",mes_df_sum["Q_tot_sys"][1]/1000)
print("Sensible coil load: ",mes_df_sum["Q_sen_sys"][1]/1000)
print("Latent coil load: ",(mes_df_sum["Q_tot_sys"][1]-mes_df_sum["Q_sen_sys"][1])/1000)
print("Total space load: ",(mes_df_sum["Q_sensible"][1]+mes_df_sum["Q_latent"][1])/1000)
print("Sensible coil load: ",mes_df_sum["Q_sensible"][1]/1000)
print("Latent coil load: ",mes_df_sum["Q_latent"][1]/1000)
mes_df_mean =  pro.component("system").variable_dataframe(frequency="M",value="mean")
print("COP: ",mes_df_mean["EER"][1])
print("T_idb: ",mes_df_mean["T_idb"][1])
print("w_i: ",pro.component("space_1").variable_dataframe(frequency="M",value="mean")["abs_humidity"][1]/1000)

Total consumption:  1478.90515008288
Compressor consumption:  1251.7691500828798
Indoor fan consumption:  154.56
Outdoor fan consumption:  72.576
Total coil load:  -5499.5855871469885
Sensible coil load:  -4276.4676201130815
Latent coil load:  -1223.1179670339068
Total space load:  -5345.025587146988
Sensible coil load:  -4121.907620113081
Latent coil load:  -1223.1179670339066
COP:  3.6141774035534704
T_idb:  26.78954366863747
w_i:  0.011112604564633642

In [4]:
mes_df_max =  pro.component("system").variable_dataframe(frequency="M",value="max")
print("COP: ",mes_df_max["EER"][1])
print("T_idb: ",mes_df_max["T_idb"][1])
print("w_i: ",pro.component("space_1").variable_dataframe(frequency="M",value="max")["abs_humidity"][1]/1000)

COP:  3.614902106756449
T_idb:  26.803683049322068
w_i:  0.011117824880624976

In [5]:
mes_df_min =  pro.component("system").variable_dataframe(frequency="M",value="min")
print("COP: ",mes_df_min["EER"][1])
print("T_idb: ",mes_df_min["T_idb"][1])
print("w_i: ",pro.component("space_1").variable_dataframe(frequency="M",value="min")["abs_humidity"][1]/1000)

COP:  3.613769477601715
T_idb:  26.781304847085824
w_i:  0.011110105617898457

In [6]:
pro.component("space_1").variable_dataframe(frequency="M",value="min" )

,temperature,abs_humidity,rel_humidity,people_convective,people_radiant,people_latent,light_convective,light_radiant,other_gains_convective,other_gains_radiant,...,solar_direct_gains,infiltration_flow,surfaces_convective,delta_int_energy,infiltration_sensible_heat,infiltration_latent_heat,system_sensible_heat,system_latent_heat,u_system_sensible_heat,u_system_latent_heat
date,,,,,,,,,,,,,,,,,,,,,
2001-01-31,26.781269,10.636867,48.364732,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-6135.741756,-1820.831744,0.0,0.0
2001-02-28,26.781305,11.110106,50.447678,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.817488,-1820.833488,0.0,0.0
2001-03-31,26.781285,11.110088,50.447916,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.798888,-1820.832046,0.0,0.0
2001-04-30,26.781268,11.110082,50.447752,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.811705,-1820.834954,0.0,0.0
2001-05-31,26.781295,11.110094,50.443019,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6136.164363,-1820.830396,0.0,0.0
2001-06-30,26.781282,11.110088,50.447827,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.808081,-1820.831245,0.0,0.0
2001-07-31,26.781270,11.110075,50.448355,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.758790,-1820.832050,0.0,0.0
2001-08-31,26.781277,11.110034,50.444619,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.816704,-1820.835147,0.0,0.0
2001-09-30,26.781278,11.110086,50.447999,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.795668,-1820.831916,0.0,0.0
2001-10-31,26.781266,11.110082,50.448430,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.751039,-1820.832354,0.0,0.0
2001-11-30,26.781284,11.110089,50.448404,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.754165,-1820.829481,0.0,0.0
2001-12-31,26.781276,11.110085,50.448595,0.0,0.0,0.0,0.0,0.0,6119.828376,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-6135.740196,-1820.830739,0.0,0.0

In [8]:
pro.simulation_dataframe()

                   dates  n_iterations last_component
0    2001-01-01 00:30:00            32        space_1
1    2001-01-01 01:30:00            36        space_1
2    2001-01-01 02:30:00            41        space_1
3    2001-01-01 03:30:00            42        space_1
4    2001-01-01 04:30:00            42        space_1
...                  ...           ...            ...
8755 2001-12-31 19:30:00            42        space_1
8756 2001-12-31 20:30:00            42        space_1
8757 2001-12-31 21:30:00            42        space_1
8758 2001-12-31 22:30:00            42        space_1
8759 2001-12-31 23:30:00            42        space_1

[8760 rows x 3 columns]