## ASHRAE 140-2023

Section 9: CASE CE300 - Comparative test base-case building and mechanical system

In [1]:
import OpenSimula as osm
import pandas as pd
import numpy as np

case_ce300_dict = {
    "name": "Case CE300",
    "time_step": 3600,
    "n_time_steps": 8760,
    "initial_time": "01/01/2001 00:00:00",
    "simulation_file_met": "meteo",
    "components": [ 
        {
            "type": "File_met",
            "name": "meteo",
            "file_type": "TMY2",
            "file_name": "../../mets/CE300.TM2"
        },    
        {
            "type": "Material",
            "name": "Insulation",
            "conductivity": 0.00308,
            "density": 1,
            "specific_heat": 1
        },
        {
            "type": "Construction",
            "name": "Adiabatic_Wall",
            "solar_alpha": [0.1,0.6],
            "lw_epsilon": [0.9,0.9],
            "materials": [
                "Insulation"
            ],
            "thicknesses": [
                1.0
            ]
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_1",
            "time_steps": [8*3600, 12*3600],
            "values": [0, 0.25, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_2",
            "time_steps": [9*3600, 9*3600],
            "values": [0, 1, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_3",
            "time_steps": [8*3600, 11*3600],
            "values": [0, 1, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_4",
            "time_steps": [8*3600, 12*3600],
            "values": [0, 1, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_5",
            "time_steps": [8*3600, 8*3600],
            "values": [0, 1, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "latent_day_6",
            "time_steps": [8*3600, 12*3600],
            "values": [0, 1, 0],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_1",
            "time_steps": [],
            "values": [0.15625],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_2",
            "time_steps": [9*3600, 9*3600],
            "values": [0.15625, 0.375, 0.15625],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_3",
            "time_steps": [8*3600, 11*3600],
            "values": [0.15625, 0.5, 0.15625],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_4",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0.375, 0.5, 0.75, 1, 0.5, 0.375],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_5",
            "time_steps": [8*3600, 8*3600],
            "values": [0.15625, 0.5, 0.15625],
            "interpolation": "STEP",
        },
        {
            "type": "Day_schedule",
            "name": "sensible_day_6",
            "time_steps": [8*3600, 4*3600, 2*3600, 2*3600, 4*3600],
            "values": [0.15625, 0.5, 0.75, 1, 0.5, 0.375],
            "interpolation": "STEP",
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_1",
            "days_schedules": ["latent_day_1"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_2",
            "days_schedules": ["latent_day_2"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_3",
            "days_schedules": ["latent_day_3"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_4",
            "days_schedules": ["latent_day_4"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_5",
            "days_schedules": ["latent_day_5"],
        },
        {
            "type": "Week_schedule",
            "name": "latent_week_6",
            "days_schedules": ["latent_day_6"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_1",
            "days_schedules": ["sensible_day_1"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_2",
            "days_schedules": ["sensible_day_2"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_3",
            "days_schedules": ["sensible_day_3"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_4",
            "days_schedules": ["sensible_day_4"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_5",
            "days_schedules": ["sensible_day_5"],
        },
        {
            "type": "Week_schedule",
            "name": "sensible_week_6",
            "days_schedules": ["sensible_day_6"],
        },
        {
            "type": "Year_schedule",
            "name": "latent_schedule",
            "periods": ["10/03", "10/04","11/04","20/04","12/10","18/10","05/11"],
            "weeks_schedules": ["latent_week_1"
                                , "latent_week_2"
                                , "latent_week_1"
                                , "latent_week_3"
                                , "latent_week_4"
                                , "latent_week_5"
                                , "latent_week_6"
                                , "latent_week_1"],
        },
        {
            "type": "Year_schedule",
            "name": "sensible_schedule",
            "periods": ["10/03", "10/04","11/04","20/04","12/10","18/10","05/11"],
            "weeks_schedules": ["sensible_week_1"
                                , "sensible_week_2"
                                , "sensible_week_1"
                                , "sensible_week_3"
                                , "sensible_week_4"
                                , "sensible_week_5"
                                , "sensible_week_6"
                                , "sensible_week_1"],
        },
        {
            "type": "Space_type",
            "name": "space_gains",
            "input_variables": ["f_l = latent_schedule.values","f_s = sensible_schedule.values"],
            "people_density": "f_l",
            "people_sensible": 0,
            "people_latent": 7.4796,            
            "light_density": "0",
            "other_gains_density": "95.704*f_s",
            "other_gains_radiant_fraction": 0,
            "infiltration": "0"
        },
        {
            "type": "Building",
            "name": "Building",
            "albedo": 0.2,
            "azimuth": 0,
            "shadow_calculation": "INSTANT"
        },
        {
            "type": "Space",
            "name": "space_1",
            "building": "Building",
            "space_type": "space_gains",
            "floor_area": 196,
            "volume": 588,
            "furniture_weight": 0
        },
        {
            "type": "Exterior_surface",
            "name": "north_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                14,
                14,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 180,
            "altitude": 0,
            "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "east_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                14,
                0,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "south_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": 0,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "west_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                14,
                0
            ],
            "width": 14,
            "height": 3,
            "azimuth": -90,
            "altitude": 0,
             "h_cv": [
                24.17,
                3.16
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "roof_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                0,
                3
            ],
            "width": 14,
            "height": 14,
            "azimuth": 0,
            "altitude": 90,
            "h_cv": [
                24.17,
                1.0
            ]
        },
        {
            "type": "Exterior_surface",
            "name": "floor_wall",
            "construction": "Adiabatic_Wall",
            "space": "space_1",
            "ref_point": [
                0,
                14,
                0
            ],
            "width": 14,
            "height": 14,
            "azimuth": 0,
            "altitude": -90,
            "h_cv": [
                24.17,
                4.13
            ]
        },
        {
            "type": "HVAC_DX_equipment",
            "name": "HVAC_equipment",
            "nominal_air_flow": 1.888,
            "nominal_total_cooling_capacity": 33277,
            "nominal_sensible_cooling_capacity": 26043,
            "nominal_cooling_power": 10937,
            "indoor_fan_power": 1242,
            "indoor_fan_operation": "CONTINUOUS",
            "nominal_cooling_conditions": [26.67,19.44,35],            
            "total_cooling_capacity_expression": "-3.762e-03 * T_odb + 1.941e-02 * T_iwb + 4.783e-03 * T_idb -2.535e-05 * T_odb**2 + 1.232e-03 * T_iwb**2 + 4.448e-04 * T_idb**2 -2.754e-04 * T_odb * T_iwb + 5.977e-05 * T_odb * T_idb -1.297e-03 * T_iwb * T_idb + 6.851e-01",
            "sensible_cooling_capacity_expression": "-4.491e-03*T_odb -3.135e-02*T_iwb -1.011e-01*T_idb -6.467e-05*T_odb**2 -4.991e-03*T_iwb**2 +6.132e-03*T_idb**2 +3.255e-04*T_odb*T_iwb -1.873e-04*T_odb*T_idb +4.163e-03*T_iwb*T_idb +4.984e-07*T_odb**3 +3.308e-05*T_iwb**3 -1.075e-04*T_idb**3 + 1.6552",            
            "cooling_power_expression": "7.990e-03 * T_odb +6.779e-05 * T_iwb + 5.339e-04 * T_idb -2.125e-05 * T_odb**2 +4.948e-04 * T_iwb**2 +1.983e-04 * T_idb**2 + 1.931e-04 * T_odb * T_iwb +7.733e-05 * T_odb * T_idb -5.698e-04 * T_iwb * T_idb + 4.978e-01",
            "EER_expression": "1 - 0.229*(1-F_load)",
            "expression_max_values": [40,35,50,30,1.5,1]
        },
        {
            "type": "HVAC_DX_system",
            "name": "system",
            "space": "space_1",
            "equipment": "HVAC_equipment",
            "supply_air_flow": 1.888,
            "outdoor_air_flow": 0.2832,
            "heating_setpoint": "20",
            "cooling_setpoint": "25",
            "system_on_off": "1"
        }
    ]
}


sim = osm.Simulation()
pro = sim.new_project("pro")
pro.read_dict(case_ce300_dict)
pro.simulate(5)

Reading project data from dictonary
Reading completed.
Checking project: Case CE300
Checking completed.
Calculating solar direct shadows ...
Calculating solar diffuse shadows ...
Simulating Case CE300: ...
5%: N_iter: 3.51
10%: N_iter: 4.33
15%: N_iter: 3.50
20%: N_iter: 4.05
25%: N_iter: 4.91
30%: N_iter: 5.69
35%: N_iter: 7.42
40%: N_iter: 7.43
45%: N_iter: 8.01
50%: N_iter: 8.27
55%: N_iter: 8.57
60%: N_iter: 8.46
65%: N_iter: 8.61
70%: N_iter: 8.33
75%: N_iter: 7.97
80%: N_iter: 6.34
85%: N_iter: 6.46
90%: N_iter: 4.32
95%: N_iter: 3.82
100%: N_iter: 3.76
Simulation completed.

In [2]:
system = pro.component("system")
sys_df=system.variable_dataframe()
sys_df["time_frac"] = -sys_df["F_load"]/sys_df["efficiency_degradation"]
sys_df["power_ve"] = sys_df["time_frac"]*930
sys_df["power_comp"] = sys_df["power"]-sys_df["indoor_fan_power"]-sys_df["power_ve"] 
sys_df["Q_total"] = sys_df["Q_sensible"]+sys_df["Q_latent"]
sys_df["COP2"] = -sys_df["Q_total"] / (sys_df["power_comp"] + sys_df["power_ve"])

In [3]:
df_sum = sys_df.resample("Y", on='date').sum()
excel = pd.DataFrame()
excel["Total_consumption"] = [df_sum["power"][0]/1000]
excel["Compressor_consumption"] = [df_sum["power_comp"][0]/1000]
excel["Outdoor_fan_consumption"] = [df_sum["power_ve"][0]/1000]
excel["Indoor_fan_consumption"] = [df_sum["indoor_fan_power"][0]/1000]
excel["Q_total"] = [-df_sum["Q_total"][0]/1000]
excel["Q_sensible"] = [-df_sum["Q_sensible"][0]/1000]
excel["Q_latent"] = [-df_sum["Q_latent"][0]/1000]
excel["COP2_mean"] = -df_sum["Q_total"][0]/(df_sum["power_comp"][0]+df_sum["power_ve"][0])

df_space_mean = pro.component("space_1").variable_dataframe(frequency="Y",value="mean")
excel["T_space_mean"] = [df_space_mean["temperature"][0]]
excel["w_space_mean"] = [df_space_mean["abs_humidity"][0]/1000]
excel["HR_space_mean"] = [df_space_mean["rel_humidity"][0]]
meteo_df = pro.component("meteo").variable_dataframe(frequency="Y", value="mean")
excel["T_ext_mean"] = [meteo_df["temperature"][0]]
excel["w_ext_mean"] = [meteo_df["abs_humidity"][0]/1000]

excel.to_clipboard()
excel

,Total_consumption,Compressor_consumption,Outdoor_fan_consumption,Indoor_fan_consumption,Q_total,Q_sensible,Q_latent,COP2_mean,T_space_mean,w_space_mean,HR_space_mean,T_ext_mean,w_ext_mean
0,34940.384111,21739.790348,2320.673763,10879.92,77806.779071,55339.242585,22467.536486,3.233802,24.118553,0.009177,47.812195,19.914452,0.011605

In [4]:
excel_max = pd.DataFrame()
excel_max["max_power"] = [sys_df["power"].max()]
excel_max["max_power_day"] = [pro.dates()[sys_df['power'].idxmax()].strftime("%d-%b")]
excel_max["max_power_hour"] = [int(pro.dates()[sys_df['power'].idxmax()].strftime("%H"))+1]
excel_max["max_Q_sen"] = [-sys_df["Q_sensible"].min()]
excel_max["max_Q_sen_day"] = [pro.dates()[sys_df['Q_sensible'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_sen_hour"] = [int(pro.dates()[sys_df['Q_sensible'].idxmin()].strftime("%H"))+1]
excel_max["max_Q_lat"] = [-sys_df["Q_latent"].min()]
excel_max["max_Q_lat_day"] = [pro.dates()[sys_df['Q_latent'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_lat_hour"] = [int(pro.dates()[sys_df['Q_latent'].idxmin()].strftime("%H"))+1]
excel_max["max_Q_tot"] = [-sys_df["Q_total"].min()]
excel_max["max_Q_tot_day"] = [pro.dates()[sys_df['Q_total'].idxmin()].strftime("%d-%b")]
excel_max["max_Q_tot_hour"] = [int(pro.dates()[sys_df['Q_total'].idxmin()].strftime("%H"))+1]
meteo_df = pro.component("meteo").variable_dataframe()
excel_max["max_T_ext"] = [meteo_df["temperature"].max()]
excel_max["max_T_ext_day"] = [pro.dates()[meteo_df['temperature'].idxmax()].strftime("%d-%b")]
excel_max["max_T_ext_hour"] = [int(pro.dates()[meteo_df['temperature'].idxmax()].strftime("%H"))+1]
excel_max["max_w_ext"] = [meteo_df["abs_humidity"].max()/1000]
excel_max["max_w_ext_day"] = [pro.dates()[meteo_df['abs_humidity'].idxmax()].strftime("%d-%b")]
excel_max["max_w_ext_hour"] = [int(pro.dates()[meteo_df['abs_humidity'].idxmax()].strftime("%H"))+1]

excel_max.to_clipboard()
excel_max

,max_power,max_power_day,max_power_hour,max_Q_sen,max_Q_sen_day,max_Q_sen_hour,max_Q_lat,max_Q_lat_day,max_Q_lat_hour,max_Q_tot,max_Q_tot_day,max_Q_tot_hour,max_T_ext,max_T_ext_day,max_T_ext_hour,max_w_ext,max_w_ext_day,max_w_ext_hour
0,11803.365496,20-Jul,15,23399.21542,20-Jul,15,9873.07062,03-Sep,15,32091.67987,20-Jul,15,35.0,20-Jul,15,0.022269,02-Oct,9

In [5]:
excel_max_2 = pd.DataFrame()
excel_max_2["max_COP2"] = [sys_df["COP2"].max()]
excel_max_2["max_COP2_day"] = [pro.dates()[sys_df['COP2'].idxmax()].strftime("%d-%b")]
excel_max_2["max_COP2_hour"] = [int(pro.dates()[sys_df['COP2'].idxmax()].strftime("%H"))+1]
excel_max_2["min_COP2"] = [sys_df["COP2"].min()]
excel_max_2["min_COP2_day"] = [pro.dates()[sys_df['COP2'].idxmin()].strftime("%d-%b")]
excel_max_2["min_COP2_hour"] = [int(pro.dates()[sys_df['COP2'].idxmin()].strftime("%H"))+1]
space_df = pro.component("space_1").variable_dataframe()
excel_max_2["max_T_spa"] = [space_df["temperature"].max()]
excel_max_2["max_T_spa_day"] = [pro.dates()[space_df['temperature'].idxmax()].strftime("%d-%b")]
excel_max_2["max_T_spa_hour"] = [int(pro.dates()[space_df['temperature'].idxmax()].strftime("%H"))+1]
excel_max_2["min_T_spa"] = [space_df["temperature"].min()]
excel_max_2["min_T_spa_day"] = [pro.dates()[space_df['temperature'].idxmin()].strftime("%d-%b")]
excel_max_2["min_T_spa_hour"] = [int(pro.dates()[space_df['temperature'].idxmin()].strftime("%H"))+1]
excel_max_2["max_w_spa"] = [space_df["abs_humidity"].max()/1000]
excel_max_2["max_w_spa_day"] = [pro.dates()[space_df['abs_humidity'].idxmax()].strftime("%d-%b")]
excel_max_2["max_w_spa_hour"] = [int(pro.dates()[space_df['abs_humidity'].idxmax()].strftime("%H"))+1]
excel_max_2["min_w_spa"] = [space_df["abs_humidity"].min()/1000]
excel_max_2["min_w_spa_day"] = [pro.dates()[space_df['abs_humidity'].idxmin()].strftime("%d-%b")]
excel_max_2["min_w_spa_hour"] = [int(pro.dates()[space_df['abs_humidity'].idxmin()].strftime("%H"))+1]
excel_max_2["max_hr_spa"] = [space_df["rel_humidity"].max()]
excel_max_2["max_hr_spa_day"] = [pro.dates()[space_df['rel_humidity'].idxmax()].strftime("%d-%b")]
excel_max_2["max_hr_spa_hour"] = [int(pro.dates()[space_df['rel_humidity'].idxmax()].strftime("%H"))+1]
excel_max_2["min_hr_spa"] = [space_df["rel_humidity"].min()]
excel_max_2["min_hr_spa_day"] = [pro.dates()[space_df['rel_humidity'].idxmin()].strftime("%d-%b")]
excel_max_2["min_hr_spa_hour"] = [int(pro.dates()[space_df['rel_humidity'].idxmin()].strftime("%H"))+1]

excel_max_2.to_clipboard()
excel_max_2

,max_COP2,max_COP2_day,max_COP2_hour,min_COP2,min_COP2_day,min_COP2_hour,max_T_spa,max_T_spa_day,max_T_spa_hour,min_T_spa,...,max_w_spa_hour,min_w_spa,min_w_spa_day,min_w_spa_hour,max_hr_spa,max_hr_spa_day,max_hr_spa_hour,min_hr_spa,min_hr_spa_day,min_hr_spa_hour
0,3.972774,20-Apr,5,2.801321,13-Jun,17,25.089731,10-Jun,16,8.179545,...,16,0.001863,11-Jan,2,69.648527,16-Nov,17,13.107929,06-Nov,6

In [6]:
intervalo = ["2001-06-28","2001-06-29"]
sys_day=system.variable_dataframe(interval=intervalo)
sys_day["time_frac"] = -sys_day["F_load"]/sys_day["efficiency_degradation"]
sys_day["power_vi"] = 1242 
sys_day["power_ve"] = sys_df["time_frac"]*930
sys_day["power_comp"] = sys_day["power"]-sys_day["power_vi"]-sys_day["power_ve"] 
sys_day["Q_total"] = sys_day["Q_sensible"]+sys_day["Q_latent"]
sys_day["COP2"] = -sys_day["Q_total"] / (sys_day["power_comp"] + sys_day["power_ve"])
day_df= pd.DataFrame()
day_df["power_comp"]=sys_day["power_comp"]
day_df["power_ve"]=sys_day["power_ve"]
day_df["Q_total"]=-sys_day["Q_total"]
day_df["Q_sensible"]=-sys_day["Q_sensible"]
day_df["Q_latent"]=-sys_day["Q_latent"]
day_df["w_i"]=pro.component("space_1").variable_dataframe(interval=intervalo)["abs_humidity"]/1000
day_df["COP2"]=sys_day["COP2"]
day_df["T_odb"]=sys_day["T_odb"]
day_df["T_idb"]=sys_day["T_idb"]
day_df["T_iwb"]=sys_day["T_iwb"]
day_df["w_o"]=pro.component("meteo").variable_dataframe(interval=intervalo)["abs_humidity"]/1000
day_df.to_clipboard()
day_df

,power_comp,power_ve,Q_total,Q_sensible,Q_latent,w_i,COP2,T_odb,T_idb,T_iwb,w_o
4272,1898.216003,237.691953,7540.892961,5818.885356,1722.007604,0.009097,3.530533,17.8,23.920,17.115524,0.011071
4273,1983.379631,245.703949,7812.408580,5988.901216,1823.507365,0.009203,3.504763,18.3,23.995,17.261596,0.011431
4274,1897.211003,237.584197,7535.906217,5818.885356,1717.020861,0.009088,3.530037,17.8,23.920,17.107931,0.011060
4275,1894.290243,237.271001,7521.413639,5818.885356,1702.528282,0.009057,3.528594,17.8,23.920,17.085790,0.011060
4276,1764.918144,224.494710,7049.871873,5614.842281,1435.029592,0.008666,3.543695,17.2,23.830,16.657587,0.010145
4277,2094.493161,254.938950,8019.891526,6363.103895,1656.787631,0.008865,3.413545,19.4,24.160,17.018006,0.010948
4278,3088.425150,337.511955,10709.953265,8267.803279,2442.149986,0.009693,3.126138,25.0,25.000,18.143204,0.013073
4279,3311.058788,351.310119,10877.900741,9016.372659,1861.528081,0.009131,2.970182,27.2,25.330,17.615940,0.011018
4280,4531.047243,465.020816,14878.725914,11939.694422,2939.031491,0.009789,2.978087,28.9,25.585,18.264594,0.011922
4281,4639.192745,474.246297,15336.263012,11940.124214,3396.138798,0.010173,2.999207,28.9,25.585,18.615839,0.012696
4282,5302.166217,519.477966,17043.174962,12688.480656,4354.694307,0.010884,2.927554,31.1,25.915,19.427314,0.014734
4283,5065.765325,502.386596,16313.024828,12518.524989,3794.499839,0.010582,2.929702,30.6,25.840,19.027329,0.013186
4284,6366.134746,633.193471,20824.518751,17377.952995,3446.565755,0.009521,2.975217,31.1,25.915,18.113284,0.011272
4285,6482.393440,638.927169,20961.397547,17581.897022,3379.500525,0.009443,2.943471,31.7,26.005,18.139037,0.011682
4286,7967.814990,779.763181,26566.874590,22441.157311,4125.717279,0.009271,3.037055,32.2,26.080,18.124730,0.012330
4287,8185.578982,796.990094,27575.848493,22440.832180,5135.016313,0.009627,3.069929,32.2,26.080,18.588990,0.014190
4288,5387.486834,523.545480,17091.498379,12891.338225,4200.160154,0.010771,2.891457,31.7,26.005,19.377089,0.014686
4289,5438.391956,530.619129,17608.511934,12686.740659,4921.771275,0.011248,2.949988,31.1,25.915,19.764490,0.015637
4290,4786.461069,489.607178,16256.963495,11734.028836,4522.934658,0.010998,3.081265,28.3,25.495,19.340365,0.014494
4291,4821.537434,498.093979,16967.236337,11359.849312,5607.387024,0.011557,3.189551,27.2,25.330,19.910048,0.016809
4292,3922.304929,405.249932,13450.497703,9015.097840,4435.399864,0.011542,3.108106,27.2,25.330,19.900049,0.016809
4293,3824.991495,398.508242,13241.184639,8845.096339,4396.088300,0.011526,3.135121,26.7,25.255,19.859926,0.016745
4294,3722.668312,391.582063,13045.664113,8641.098055,4404.566058,0.011549,3.170848,26.1,25.165,19.852355,0.016803
4295,3768.334607,395.684679,13244.466114,8641.111428,4603.354686,0.011686,3.180693,26.1,25.165,19.988972,0.017240